// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: protos/vacancy.proto

package vacancy_api

import (
	common "github.com/IvanDrf/work-hunter/pkg/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RemoteType int32

const (
	RemoteType_OFFICE RemoteType = 0
	RemoteType_REMOTE RemoteType = 1
	RemoteType_HYBRID RemoteType = 2
	RemoteType_ANY    RemoteType = 3
)

// Enum value maps for RemoteType.
var (
	RemoteType_name = map[int32]string{
		0: "OFFICE",
		1: "REMOTE",
		2: "HYBRID",
		3: "ANY",
	}
	RemoteType_value = map[string]int32{
		"OFFICE": 0,
		"REMOTE": 1,
		"HYBRID": 2,
		"ANY":    3,
	}
)

func (x RemoteType) Enum() *RemoteType {
	p := new(RemoteType)
	*p = x
	return p
}

func (x RemoteType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RemoteType) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_vacancy_proto_enumTypes[0].Descriptor()
}

func (RemoteType) Type() protoreflect.EnumType {
	return &file_protos_vacancy_proto_enumTypes[0]
}

func (x RemoteType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RemoteType.Descriptor instead.
func (RemoteType) EnumDescriptor() ([]byte, []int) {
	return file_protos_vacancy_proto_rawDescGZIP(), []int{0}
}

type TimeType int32

const (
	TimeType_FULL TimeType = 0
	TimeType_PART TimeType = 1
)

// Enum value maps for TimeType.
var (
	TimeType_name = map[int32]string{
		0: "FULL",
		1: "PART",
	}
	TimeType_value = map[string]int32{
		"FULL": 0,
		"PART": 1,
	}
)

func (x TimeType) Enum() *TimeType {
	p := new(TimeType)
	*p = x
	return p
}

func (x TimeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TimeType) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_vacancy_proto_enumTypes[1].Descriptor()
}

func (TimeType) Type() protoreflect.EnumType {
	return &file_protos_vacancy_proto_enumTypes[1]
}

func (x TimeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TimeType.Descriptor instead.
func (TimeType) EnumDescriptor() ([]byte, []int) {
	return file_protos_vacancy_proto_rawDescGZIP(), []int{1}
}

type Currency int32

const (
	Currency_RUB Currency = 0
	Currency_USD Currency = 1
	Currency_EUR Currency = 2
)

// Enum value maps for Currency.
var (
	Currency_name = map[int32]string{
		0: "RUB",
		1: "USD",
		2: "EUR",
	}
	Currency_value = map[string]int32{
		"RUB": 0,
		"USD": 1,
		"EUR": 2,
	}
)

func (x Currency) Enum() *Currency {
	p := new(Currency)
	*p = x
	return p
}

func (x Currency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Currency) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_vacancy_proto_enumTypes[2].Descriptor()
}

func (Currency) Type() protoreflect.EnumType {
	return &file_protos_vacancy_proto_enumTypes[2]
}

func (x Currency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Currency.Descriptor instead.
func (Currency) EnumDescriptor() ([]byte, []int) {
	return file_protos_vacancy_proto_rawDescGZIP(), []int{2}
}

type VacancyStatus int32

const (
	VacancyStatus_MODERATING VacancyStatus = 0
	VacancyStatus_PUBLISHED  VacancyStatus = 1
	VacancyStatus_CLOSED     VacancyStatus = 2
	VacancyStatus_DELETED    VacancyStatus = 3
)

// Enum value maps for VacancyStatus.
var (
	VacancyStatus_name = map[int32]string{
		0: "MODERATING",
		1: "PUBLISHED",
		2: "CLOSED",
		3: "DELETED",
	}
	VacancyStatus_value = map[string]int32{
		"MODERATING": 0,
		"PUBLISHED":  1,
		"CLOSED":     2,
		"DELETED":    3,
	}
)

func (x VacancyStatus) Enum() *VacancyStatus {
	p := new(VacancyStatus)
	*p = x
	return p
}

func (x VacancyStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VacancyStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_vacancy_proto_enumTypes[3].Descriptor()
}

func (VacancyStatus) Type() protoreflect.EnumType {
	return &file_protos_vacancy_proto_enumTypes[3]
}

func (x VacancyStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VacancyStatus.Descriptor instead.
func (VacancyStatus) EnumDescriptor() ([]byte, []int) {
	return file_protos_vacancy_proto_rawDescGZIP(), []int{3}
}

type ResponseStatus int32

const (
	ResponseStatus_SUCCESS   ResponseStatus = 0
	ResponseStatus_FAILED    ResponseStatus = 1
	ResponseStatus_NOT_FOUND ResponseStatus = 2
	ResponseStatus_FORBIDDEN ResponseStatus = 3
)

// Enum value maps for ResponseStatus.
var (
	ResponseStatus_name = map[int32]string{
		0: "SUCCESS",
		1: "FAILED",
		2: "NOT_FOUND",
		3: "FORBIDDEN",
	}
	ResponseStatus_value = map[string]int32{
		"SUCCESS":   0,
		"FAILED":    1,
		"NOT_FOUND": 2,
		"FORBIDDEN": 3,
	}
)

func (x ResponseStatus) Enum() *ResponseStatus {
	p := new(ResponseStatus)
	*p = x
	return p
}

func (x ResponseStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_vacancy_proto_enumTypes[4].Descriptor()
}

func (ResponseStatus) Type() protoreflect.EnumType {
	return &file_protos_vacancy_proto_enumTypes[4]
}

func (x ResponseStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseStatus.Descriptor instead.
func (ResponseStatus) EnumDescriptor() ([]byte, []int) {
	return file_protos_vacancy_proto_rawDescGZIP(), []int{4}
}

type OrderBy int32

const (
	OrderBy_DATE              OrderBy = 0
	OrderBy_VIEWS             OrderBy = 1
	OrderBy_APPLICATIONS_ASC  OrderBy = 2
	OrderBy_APPLICATIONS_DESC OrderBy = 3
)

// Enum value maps for OrderBy.
var (
	OrderBy_name = map[int32]string{
		0: "DATE",
		1: "VIEWS",
		2: "APPLICATIONS_ASC",
		3: "APPLICATIONS_DESC",
	}
	OrderBy_value = map[string]int32{
		"DATE":              0,
		"VIEWS":             1,
		"APPLICATIONS_ASC":  2,
		"APPLICATIONS_DESC": 3,
	}
)

func (x OrderBy) Enum() *OrderBy {
	p := new(OrderBy)
	*p = x
	return p
}

func (x OrderBy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderBy) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_vacancy_proto_enumTypes[5].Descriptor()
}

func (OrderBy) Type() protoreflect.EnumType {
	return &file_protos_vacancy_proto_enumTypes[5]
}

func (x OrderBy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderBy.Descriptor instead.
func (OrderBy) EnumDescriptor() ([]byte, []int) {
	return file_protos_vacancy_proto_rawDescGZIP(), []int{5}
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Status        ResponseStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=vacancy.ResponseStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_protos_vacancy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vacancy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_protos_vacancy_proto_rawDescGZIP(), []int{0}
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Response) GetStatus() ResponseStatus {
	if x != nil {
		return x.Status
	}
	return ResponseStatus_SUCCESS
}

type VacancyInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	VacancyId         *uint64                `protobuf:"varint,1,opt,name=vacancy_id,json=vacancyId,proto3,oneof" json:"vacancy_id,omitempty"`
	Title             string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description       string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Requirements      string                 `protobuf:"bytes,4,opt,name=requirements,proto3" json:"requirements,omitempty"`
	Conditions        string                 `protobuf:"bytes,5,opt,name=conditions,proto3" json:"conditions,omitempty"`
	SalaryMin         *uint64                `protobuf:"varint,6,opt,name=salary_min,json=salaryMin,proto3,oneof" json:"salary_min,omitempty"`
	SalaryMax         *uint64                `protobuf:"varint,7,opt,name=salary_max,json=salaryMax,proto3,oneof" json:"salary_max,omitempty"`
	Currency          Currency               `protobuf:"varint,8,opt,name=currency,proto3,enum=vacancy.Currency" json:"currency,omitempty"`
	City              *string                `protobuf:"bytes,9,opt,name=city,proto3,oneof" json:"city,omitempty"`
	Metro             *string                `protobuf:"bytes,10,opt,name=metro,proto3,oneof" json:"metro,omitempty"`
	IsCityValid       bool                   `protobuf:"varint,27,opt,name=is_city_valid,json=isCityValid,proto3" json:"is_city_valid,omitempty"`
	IsMetroValid      bool                   `protobuf:"varint,26,opt,name=is_metro_valid,json=isMetroValid,proto3" json:"is_metro_valid,omitempty"`
	RemoteType        RemoteType             `protobuf:"varint,11,opt,name=remote_type,json=remoteType,proto3,enum=vacancy.RemoteType" json:"remote_type,omitempty"`
	TimeType          TimeType               `protobuf:"varint,12,opt,name=time_type,json=timeType,proto3,enum=vacancy.TimeType" json:"time_type,omitempty"`
	ExperienceMin     *uint32                `protobuf:"varint,13,opt,name=experience_min,json=experienceMin,proto3,oneof" json:"experience_min,omitempty"`
	ExperienceMax     *uint32                `protobuf:"varint,14,opt,name=experience_max,json=experienceMax,proto3,oneof" json:"experience_max,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3,oneof" json:"created_at,omitempty"`
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=updated_at,json=updatedAt,proto3,oneof" json:"updated_at,omitempty"`
	PublishedAt       *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=published_at,json=publishedAt,proto3,oneof" json:"published_at,omitempty"`
	ClosedAt          *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=closed_at,json=closedAt,proto3,oneof" json:"closed_at,omitempty"`
	Status            *VacancyStatus         `protobuf:"varint,19,opt,name=status,proto3,enum=vacancy.VacancyStatus,oneof" json:"status,omitempty"`
	ModeratedTime     *timestamppb.Timestamp `protobuf:"bytes,20,opt,name=moderated_time,json=moderatedTime,proto3,oneof" json:"moderated_time,omitempty"`
	ModeratorComments *string                `protobuf:"bytes,21,opt,name=moderator_comments,json=moderatorComments,proto3,oneof" json:"moderator_comments,omitempty"`
	Views             *uint64                `protobuf:"varint,22,opt,name=views,proto3,oneof" json:"views,omitempty"`
	ApplicationsCount *uint64                `protobuf:"varint,23,opt,name=applications_count,json=applicationsCount,proto3,oneof" json:"applications_count,omitempty"`
	Tags              []string               `protobuf:"bytes,24,rep,name=tags,proto3" json:"tags,omitempty"` // vacancies tags: golang, javascript, manager
	AuthorName        string                 `protobuf:"bytes,25,opt,name=author_name,json=authorName,proto3" json:"author_name,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VacancyInfo) Reset() {
	*x = VacancyInfo{}
	mi := &file_protos_vacancy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VacancyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VacancyInfo) ProtoMessage() {}

func (x *VacancyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vacancy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VacancyInfo.ProtoReflect.Descriptor instead.
func (*VacancyInfo) Descriptor() ([]byte, []int) {
	return file_protos_vacancy_proto_rawDescGZIP(), []int{1}
}

func (x *VacancyInfo) GetVacancyId() uint64 {
	if x != nil && x.VacancyId != nil {
		return *x.VacancyId
	}
	return 0
}

func (x *VacancyInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VacancyInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *VacancyInfo) GetRequirements() string {
	if x != nil {
		return x.Requirements
	}
	return ""
}

func (x *VacancyInfo) GetConditions() string {
	if x != nil {
		return x.Conditions
	}
	return ""
}

func (x *VacancyInfo) GetSalaryMin() uint64 {
	if x != nil && x.SalaryMin != nil {
		return *x.SalaryMin
	}
	return 0
}

func (x *VacancyInfo) GetSalaryMax() uint64 {
	if x != nil && x.SalaryMax != nil {
		return *x.SalaryMax
	}
	return 0
}

func (x *VacancyInfo) GetCurrency() Currency {
	if x != nil {
		return x.Currency
	}
	return Currency_RUB
}

func (x *VacancyInfo) GetCity() string {
	if x != nil && x.City != nil {
		return *x.City
	}
	return ""
}

func (x *VacancyInfo) GetMetro() string {
	if x != nil && x.Metro != nil {
		return *x.Metro
	}
	return ""
}

func (x *VacancyInfo) GetIsCityValid() bool {
	if x != nil {
		return x.IsCityValid
	}
	return false
}

func (x *VacancyInfo) GetIsMetroValid() bool {
	if x != nil {
		return x.IsMetroValid
	}
	return false
}

func (x *VacancyInfo) GetRemoteType() RemoteType {
	if x != nil {
		return x.RemoteType
	}
	return RemoteType_OFFICE
}

func (x *VacancyInfo) GetTimeType() TimeType {
	if x != nil {
		return x.TimeType
	}
	return TimeType_FULL
}

func (x *VacancyInfo) GetExperienceMin() uint32 {
	if x != nil && x.ExperienceMin != nil {
		return *x.ExperienceMin
	}
	return 0
}

func (x *VacancyInfo) GetExperienceMax() uint32 {
	if x != nil && x.ExperienceMax != nil {
		return *x.ExperienceMax
	}
	return 0
}

func (x *VacancyInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *VacancyInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *VacancyInfo) GetPublishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

func (x *VacancyInfo) GetClosedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ClosedAt
	}
	return nil
}

func (x *VacancyInfo) GetStatus() VacancyStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return VacancyStatus_MODERATING
}

func (x *VacancyInfo) GetModeratedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ModeratedTime
	}
	return nil
}

func (x *VacancyInfo) GetModeratorComments() string {
	if x != nil && x.ModeratorComments != nil {
		return *x.ModeratorComments
	}
	return ""
}

func (x *VacancyInfo) GetViews() uint64 {
	if x != nil && x.Views != nil {
		return *x.Views
	}
	return 0
}

func (x *VacancyInfo) GetApplicationsCount() uint64 {
	if x != nil && x.ApplicationsCount != nil {
		return *x.ApplicationsCount
	}
	return 0
}

func (x *VacancyInfo) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *VacancyInfo) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

type CreateVacancyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Requirements  string                 `protobuf:"bytes,3,opt,name=requirements,proto3" json:"requirements,omitempty"`
	Conditions    string                 `protobuf:"bytes,4,opt,name=conditions,proto3" json:"conditions,omitempty"`
	SalaryMin     *uint64                `protobuf:"varint,5,opt,name=salary_min,json=salaryMin,proto3,oneof" json:"salary_min,omitempty"`
	SalaryMax     *uint64                `protobuf:"varint,6,opt,name=salary_max,json=salaryMax,proto3,oneof" json:"salary_max,omitempty"`
	Currency      Currency               `protobuf:"varint,7,opt,name=currency,proto3,enum=vacancy.Currency" json:"currency,omitempty"`
	City          *string                `protobuf:"bytes,8,opt,name=city,proto3,oneof" json:"city,omitempty"`
	Metro         *string                `protobuf:"bytes,9,opt,name=metro,proto3,oneof" json:"metro,omitempty"`
	RemoteType    RemoteType             `protobuf:"varint,10,opt,name=remote_type,json=remoteType,proto3,enum=vacancy.RemoteType" json:"remote_type,omitempty"`
	TimeType      TimeType               `protobuf:"varint,11,opt,name=time_type,json=timeType,proto3,enum=vacancy.TimeType" json:"time_type,omitempty"`
	ExperienceMin *uint32                `protobuf:"varint,12,opt,name=experience_min,json=experienceMin,proto3,oneof" json:"experience_min,omitempty"`
	ExperienceMax *uint32                `protobuf:"varint,13,opt,name=experience_max,json=experienceMax,proto3,oneof" json:"experience_max,omitempty"`
	Tags          []string               `protobuf:"bytes,14,rep,name=tags,proto3" json:"tags,omitempty"` // vacancies tags: golang, javascript, manager
	UserInfo      *common.FullUserInfo   `protobuf:"bytes,15,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVacancyRequest) Reset() {
	*x = CreateVacancyRequest{}
	mi := &file_protos_vacancy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVacancyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVacancyRequest) ProtoMessage() {}

func (x *CreateVacancyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vacancy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVacancyRequest.ProtoReflect.Descriptor instead.
func (*CreateVacancyRequest) Descriptor() ([]byte, []int) {
	return file_protos_vacancy_proto_rawDescGZIP(), []int{2}
}

func (x *CreateVacancyRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateVacancyRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateVacancyRequest) GetRequirements() string {
	if x != nil {
		return x.Requirements
	}
	return ""
}

func (x *CreateVacancyRequest) GetConditions() string {
	if x != nil {
		return x.Conditions
	}
	return ""
}

func (x *CreateVacancyRequest) GetSalaryMin() uint64 {
	if x != nil && x.SalaryMin != nil {
		return *x.SalaryMin
	}
	return 0
}

func (x *CreateVacancyRequest) GetSalaryMax() uint64 {
	if x != nil && x.SalaryMax != nil {
		return *x.SalaryMax
	}
	return 0
}

func (x *CreateVacancyRequest) GetCurrency() Currency {
	if x != nil {
		return x.Currency
	}
	return Currency_RUB
}

func (x *CreateVacancyRequest) GetCity() string {
	if x != nil && x.City != nil {
		return *x.City
	}
	return ""
}

func (x *CreateVacancyRequest) GetMetro() string {
	if x != nil && x.Metro != nil {
		return *x.Metro
	}
	return ""
}

func (x *CreateVacancyRequest) GetRemoteType() RemoteType {
	if x != nil {
		return x.RemoteType
	}
	return RemoteType_OFFICE
}

func (x *CreateVacancyRequest) GetTimeType() TimeType {
	if x != nil {
		return x.TimeType
	}
	return TimeType_FULL
}

func (x *CreateVacancyRequest) GetExperienceMin() uint32 {
	if x != nil && x.ExperienceMin != nil {
		return *x.ExperienceMin
	}
	return 0
}

func (x *CreateVacancyRequest) GetExperienceMax() uint32 {
	if x != nil && x.ExperienceMax != nil {
		return *x.ExperienceMax
	}
	return 0
}

func (x *CreateVacancyRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateVacancyRequest) GetUserInfo() *common.FullUserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

type UpdateVacancyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VacancyId     uint64                 `protobuf:"varint,1,opt,name=vacancy_id,json=vacancyId,proto3" json:"vacancy_id,omitempty"`
	Title         *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Requirements  *string                `protobuf:"bytes,4,opt,name=requirements,proto3,oneof" json:"requirements,omitempty"`
	Conditions    *string                `protobuf:"bytes,5,opt,name=conditions,proto3,oneof" json:"conditions,omitempty"`
	SalaryMin     *uint64                `protobuf:"varint,6,opt,name=salary_min,json=salaryMin,proto3,oneof" json:"salary_min,omitempty"`
	SalaryMax     *uint64                `protobuf:"varint,7,opt,name=salary_max,json=salaryMax,proto3,oneof" json:"salary_max,omitempty"`
	Currency      *Currency              `protobuf:"varint,8,opt,name=currency,proto3,enum=vacancy.Currency,oneof" json:"currency,omitempty"`
	City          *string                `protobuf:"bytes,9,opt,name=city,proto3,oneof" json:"city,omitempty"`
	Metro         *string                `protobuf:"bytes,10,opt,name=metro,proto3,oneof" json:"metro,omitempty"`
	RemoteType    *RemoteType            `protobuf:"varint,11,opt,name=remote_type,json=remoteType,proto3,enum=vacancy.RemoteType,oneof" json:"remote_type,omitempty"`
	TimeType      *TimeType              `protobuf:"varint,12,opt,name=time_type,json=timeType,proto3,enum=vacancy.TimeType,oneof" json:"time_type,omitempty"`
	ExperienceMin *uint32                `protobuf:"varint,13,opt,name=experience_min,json=experienceMin,proto3,oneof" json:"experience_min,omitempty"`
	ExperienceMax *uint32                `protobuf:"varint,14,opt,name=experience_max,json=experienceMax,proto3,oneof" json:"experience_max,omitempty"`
	Tags          []string               `protobuf:"bytes,24,rep,name=tags,proto3" json:"tags,omitempty"` // vacancies tags: golang, javascript, manager
	UpdateTags    bool                   `protobuf:"varint,26,opt,name=update_tags,json=updateTags,proto3" json:"update_tags,omitempty"`
	UserInfo      *common.UserInfo       `protobuf:"bytes,25,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVacancyRequest) Reset() {
	*x = UpdateVacancyRequest{}
	mi := &file_protos_vacancy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVacancyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVacancyRequest) ProtoMessage() {}

func (x *UpdateVacancyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vacancy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVacancyRequest.ProtoReflect.Descriptor instead.
func (*UpdateVacancyRequest) Descriptor() ([]byte, []int) {
	return file_protos_vacancy_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateVacancyRequest) GetVacancyId() uint64 {
	if x != nil {
		return x.VacancyId
	}
	return 0
}

func (x *UpdateVacancyRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateVacancyRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateVacancyRequest) GetRequirements() string {
	if x != nil && x.Requirements != nil {
		return *x.Requirements
	}
	return ""
}

func (x *UpdateVacancyRequest) GetConditions() string {
	if x != nil && x.Conditions != nil {
		return *x.Conditions
	}
	return ""
}

func (x *UpdateVacancyRequest) GetSalaryMin() uint64 {
	if x != nil && x.SalaryMin != nil {
		return *x.SalaryMin
	}
	return 0
}

func (x *UpdateVacancyRequest) GetSalaryMax() uint64 {
	if x != nil && x.SalaryMax != nil {
		return *x.SalaryMax
	}
	return 0
}

func (x *UpdateVacancyRequest) GetCurrency() Currency {
	if x != nil && x.Currency != nil {
		return *x.Currency
	}
	return Currency_RUB
}

func (x *UpdateVacancyRequest) GetCity() string {
	if x != nil && x.City != nil {
		return *x.City
	}
	return ""
}

func (x *UpdateVacancyRequest) GetMetro() string {
	if x != nil && x.Metro != nil {
		return *x.Metro
	}
	return ""
}

func (x *UpdateVacancyRequest) GetRemoteType() RemoteType {
	if x != nil && x.RemoteType != nil {
		return *x.RemoteType
	}
	return RemoteType_OFFICE
}

func (x *UpdateVacancyRequest) GetTimeType() TimeType {
	if x != nil && x.TimeType != nil {
		return *x.TimeType
	}
	return TimeType_FULL
}

func (x *UpdateVacancyRequest) GetExperienceMin() uint32 {
	if x != nil && x.ExperienceMin != nil {
		return *x.ExperienceMin
	}
	return 0
}

func (x *UpdateVacancyRequest) GetExperienceMax() uint32 {
	if x != nil && x.ExperienceMax != nil {
		return *x.ExperienceMax
	}
	return 0
}

func (x *UpdateVacancyRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UpdateVacancyRequest) GetUpdateTags() bool {
	if x != nil {
		return x.UpdateTags
	}
	return false
}

func (x *UpdateVacancyRequest) GetUserInfo() *common.UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

type DeleteVacancyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VacancyId     uint64                 `protobuf:"varint,1,opt,name=vacancy_id,json=vacancyId,proto3" json:"vacancy_id,omitempty"`
	UserInfo      *common.UserInfo       `protobuf:"bytes,2,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVacancyRequest) Reset() {
	*x = DeleteVacancyRequest{}
	mi := &file_protos_vacancy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVacancyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVacancyRequest) ProtoMessage() {}

func (x *DeleteVacancyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vacancy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVacancyRequest.ProtoReflect.Descriptor instead.
func (*DeleteVacancyRequest) Descriptor() ([]byte, []int) {
	return file_protos_vacancy_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteVacancyRequest) GetVacancyId() uint64 {
	if x != nil {
		return x.VacancyId
	}
	return 0
}

func (x *DeleteVacancyRequest) GetUserInfo() *common.UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

type FindVacancyByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VacancyId     uint64                 `protobuf:"varint,1,opt,name=vacancy_id,json=vacancyId,proto3" json:"vacancy_id,omitempty"`
	UserInfo      *common.UserInfo       `protobuf:"bytes,2,opt,name=user_info,json=userInfo,proto3,oneof" json:"user_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindVacancyByIDRequest) Reset() {
	*x = FindVacancyByIDRequest{}
	mi := &file_protos_vacancy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindVacancyByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindVacancyByIDRequest) ProtoMessage() {}

func (x *FindVacancyByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vacancy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindVacancyByIDRequest.ProtoReflect.Descriptor instead.
func (*FindVacancyByIDRequest) Descriptor() ([]byte, []int) {
	return file_protos_vacancy_proto_rawDescGZIP(), []int{5}
}

func (x *FindVacancyByIDRequest) GetVacancyId() uint64 {
	if x != nil {
		return x.VacancyId
	}
	return 0
}

func (x *FindVacancyByIDRequest) GetUserInfo() *common.UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

type FindVacancyByTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []string               `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint32                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	OrderBy       *OrderBy               `protobuf:"varint,4,opt,name=order_by,json=orderBy,proto3,enum=vacancy.OrderBy,oneof" json:"order_by,omitempty"`
	UserInfo      *common.UserInfo       `protobuf:"bytes,5,opt,name=user_info,json=userInfo,proto3,oneof" json:"user_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindVacancyByTagsRequest) Reset() {
	*x = FindVacancyByTagsRequest{}
	mi := &file_protos_vacancy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindVacancyByTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindVacancyByTagsRequest) ProtoMessage() {}

func (x *FindVacancyByTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vacancy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindVacancyByTagsRequest.ProtoReflect.Descriptor instead.
func (*FindVacancyByTagsRequest) Descriptor() ([]byte, []int) {
	return file_protos_vacancy_proto_rawDescGZIP(), []int{6}
}

func (x *FindVacancyByTagsRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *FindVacancyByTagsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *FindVacancyByTagsRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FindVacancyByTagsRequest) GetOrderBy() OrderBy {
	if x != nil && x.OrderBy != nil {
		return *x.OrderBy
	}
	return OrderBy_DATE
}

func (x *FindVacancyByTagsRequest) GetUserInfo() *common.UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

type Vacancies struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vacancies     []*VacancyInfo         `protobuf:"bytes,1,rep,name=vacancies,proto3" json:"vacancies,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint32                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vacancies) Reset() {
	*x = Vacancies{}
	mi := &file_protos_vacancy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vacancies) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vacancies) ProtoMessage() {}

func (x *Vacancies) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vacancy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vacancies.ProtoReflect.Descriptor instead.
func (*Vacancies) Descriptor() ([]byte, []int) {
	return file_protos_vacancy_proto_rawDescGZIP(), []int{7}
}

func (x *Vacancies) GetVacancies() []*VacancyInfo {
	if x != nil {
		return x.Vacancies
	}
	return nil
}

func (x *Vacancies) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Vacancies) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type FindVacanciesByAuthorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorName    string                 `protobuf:"bytes,1,opt,name=author_name,json=authorName,proto3" json:"author_name,omitempty"` // author name
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint32                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	OrderBy       *OrderBy               `protobuf:"varint,4,opt,name=order_by,json=orderBy,proto3,enum=vacancy.OrderBy,oneof" json:"order_by,omitempty"`
	UserInfo      *common.UserInfo       `protobuf:"bytes,5,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindVacanciesByAuthorRequest) Reset() {
	*x = FindVacanciesByAuthorRequest{}
	mi := &file_protos_vacancy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindVacanciesByAuthorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindVacanciesByAuthorRequest) ProtoMessage() {}

func (x *FindVacanciesByAuthorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vacancy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindVacanciesByAuthorRequest.ProtoReflect.Descriptor instead.
func (*FindVacanciesByAuthorRequest) Descriptor() ([]byte, []int) {
	return file_protos_vacancy_proto_rawDescGZIP(), []int{8}
}

func (x *FindVacanciesByAuthorRequest) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

func (x *FindVacanciesByAuthorRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *FindVacanciesByAuthorRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FindVacanciesByAuthorRequest) GetOrderBy() OrderBy {
	if x != nil && x.OrderBy != nil {
		return *x.OrderBy
	}
	return OrderBy_DATE
}

func (x *FindVacanciesByAuthorRequest) GetUserInfo() *common.UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

type FindVacanciesByAuthorIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         uint32                 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint32                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	OrderBy       *OrderBy               `protobuf:"varint,3,opt,name=order_by,json=orderBy,proto3,enum=vacancy.OrderBy,oneof" json:"order_by,omitempty"`
	UserInfo      *common.UserInfo       `protobuf:"bytes,4,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindVacanciesByAuthorIDRequest) Reset() {
	*x = FindVacanciesByAuthorIDRequest{}
	mi := &file_protos_vacancy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindVacanciesByAuthorIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindVacanciesByAuthorIDRequest) ProtoMessage() {}

func (x *FindVacanciesByAuthorIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vacancy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindVacanciesByAuthorIDRequest.ProtoReflect.Descriptor instead.
func (*FindVacanciesByAuthorIDRequest) Descriptor() ([]byte, []int) {
	return file_protos_vacancy_proto_rawDescGZIP(), []int{9}
}

func (x *FindVacanciesByAuthorIDRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *FindVacanciesByAuthorIDRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FindVacanciesByAuthorIDRequest) GetOrderBy() OrderBy {
	if x != nil && x.OrderBy != nil {
		return *x.OrderBy
	}
	return OrderBy_DATE
}

func (x *FindVacanciesByAuthorIDRequest) GetUserInfo() *common.UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

type FindVacanciesByTitleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint32                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	OrderBy       *OrderBy               `protobuf:"varint,4,opt,name=order_by,json=orderBy,proto3,enum=vacancy.OrderBy,oneof" json:"order_by,omitempty"`
	UserInfo      *common.UserInfo       `protobuf:"bytes,5,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindVacanciesByTitleRequest) Reset() {
	*x = FindVacanciesByTitleRequest{}
	mi := &file_protos_vacancy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindVacanciesByTitleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindVacanciesByTitleRequest) ProtoMessage() {}

func (x *FindVacanciesByTitleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vacancy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindVacanciesByTitleRequest.ProtoReflect.Descriptor instead.
func (*FindVacanciesByTitleRequest) Descriptor() ([]byte, []int) {
	return file_protos_vacancy_proto_rawDescGZIP(), []int{10}
}

func (x *FindVacanciesByTitleRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *FindVacanciesByTitleRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *FindVacanciesByTitleRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FindVacanciesByTitleRequest) GetOrderBy() OrderBy {
	if x != nil && x.OrderBy != nil {
		return *x.OrderBy
	}
	return OrderBy_DATE
}

func (x *FindVacanciesByTitleRequest) GetUserInfo() *common.UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

type SetVacancyStatusRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	VacancyId         uint64                 `protobuf:"varint,1,opt,name=vacancy_id,json=vacancyId,proto3" json:"vacancy_id,omitempty"`
	Status            VacancyStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=vacancy.VacancyStatus" json:"status,omitempty"`
	ModeratorComments string                 `protobuf:"bytes,3,opt,name=moderator_comments,json=moderatorComments,proto3" json:"moderator_comments,omitempty"`
	UserInfo          *common.UserInfo       `protobuf:"bytes,4,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SetVacancyStatusRequest) Reset() {
	*x = SetVacancyStatusRequest{}
	mi := &file_protos_vacancy_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetVacancyStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetVacancyStatusRequest) ProtoMessage() {}

func (x *SetVacancyStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vacancy_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetVacancyStatusRequest.ProtoReflect.Descriptor instead.
func (*SetVacancyStatusRequest) Descriptor() ([]byte, []int) {
	return file_protos_vacancy_proto_rawDescGZIP(), []int{11}
}

func (x *SetVacancyStatusRequest) GetVacancyId() uint64 {
	if x != nil {
		return x.VacancyId
	}
	return 0
}

func (x *SetVacancyStatusRequest) GetStatus() VacancyStatus {
	if x != nil {
		return x.Status
	}
	return VacancyStatus_MODERATING
}

func (x *SetVacancyStatusRequest) GetModeratorComments() string {
	if x != nil {
		return x.ModeratorComments
	}
	return ""
}

func (x *SetVacancyStatusRequest) GetUserInfo() *common.UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

var File_protos_vacancy_proto protoreflect.FileDescriptor

const file_protos_vacancy_proto_rawDesc = "" +
	"\n" +
	"\x14protos/vacancy.proto\x12\avacancy\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\fcommon.proto\"U\n" +
	"\bResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12/\n" +
	"\x06status\x18\x02 \x01(\x0e2\x17.vacancy.ResponseStatusR\x06status\"\x90\v\n" +
	"\vVacancyInfo\x12\"\n" +
	"\n" +
	"vacancy_id\x18\x01 \x01(\x04H\x00R\tvacancyId\x88\x01\x01\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\"\n" +
	"\frequirements\x18\x04 \x01(\tR\frequirements\x12\x1e\n" +
	"\n" +
	"conditions\x18\x05 \x01(\tR\n" +
	"conditions\x12\"\n" +
	"\n" +
	"salary_min\x18\x06 \x01(\x04H\x01R\tsalaryMin\x88\x01\x01\x12\"\n" +
	"\n" +
	"salary_max\x18\a \x01(\x04H\x02R\tsalaryMax\x88\x01\x01\x12-\n" +
	"\bcurrency\x18\b \x01(\x0e2\x11.vacancy.CurrencyR\bcurrency\x12\x17\n" +
	"\x04city\x18\t \x01(\tH\x03R\x04city\x88\x01\x01\x12\x19\n" +
	"\x05metro\x18\n" +
	" \x01(\tH\x04R\x05metro\x88\x01\x01\x12\"\n" +
	"\ris_city_valid\x18\x1b \x01(\bR\visCityValid\x12$\n" +
	"\x0eis_metro_valid\x18\x1a \x01(\bR\fisMetroValid\x124\n" +
	"\vremote_type\x18\v \x01(\x0e2\x13.vacancy.RemoteTypeR\n" +
	"remoteType\x12.\n" +
	"\ttime_type\x18\f \x01(\x0e2\x11.vacancy.TimeTypeR\btimeType\x12*\n" +
	"\x0eexperience_min\x18\r \x01(\rH\x05R\rexperienceMin\x88\x01\x01\x12*\n" +
	"\x0eexperience_max\x18\x0e \x01(\rH\x06R\rexperienceMax\x88\x01\x01\x12>\n" +
	"\n" +
	"created_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampH\aR\tcreatedAt\x88\x01\x01\x12>\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampH\bR\tupdatedAt\x88\x01\x01\x12B\n" +
	"\fpublished_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampH\tR\vpublishedAt\x88\x01\x01\x12<\n" +
	"\tclosed_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampH\n" +
	"R\bclosedAt\x88\x01\x01\x123\n" +
	"\x06status\x18\x13 \x01(\x0e2\x16.vacancy.VacancyStatusH\vR\x06status\x88\x01\x01\x12F\n" +
	"\x0emoderated_time\x18\x14 \x01(\v2\x1a.google.protobuf.TimestampH\fR\rmoderatedTime\x88\x01\x01\x122\n" +
	"\x12moderator_comments\x18\x15 \x01(\tH\rR\x11moderatorComments\x88\x01\x01\x12\x19\n" +
	"\x05views\x18\x16 \x01(\x04H\x0eR\x05views\x88\x01\x01\x122\n" +
	"\x12applications_count\x18\x17 \x01(\x04H\x0fR\x11applicationsCount\x88\x01\x01\x12\x12\n" +
	"\x04tags\x18\x18 \x03(\tR\x04tags\x12\x1f\n" +
	"\vauthor_name\x18\x19 \x01(\tR\n" +
	"authorNameB\r\n" +
	"\v_vacancy_idB\r\n" +
	"\v_salary_minB\r\n" +
	"\v_salary_maxB\a\n" +
	"\x05_cityB\b\n" +
	"\x06_metroB\x11\n" +
	"\x0f_experience_minB\x11\n" +
	"\x0f_experience_maxB\r\n" +
	"\v_created_atB\r\n" +
	"\v_updated_atB\x0f\n" +
	"\r_published_atB\f\n" +
	"\n" +
	"_closed_atB\t\n" +
	"\a_statusB\x11\n" +
	"\x0f_moderated_timeB\x15\n" +
	"\x13_moderator_commentsB\b\n" +
	"\x06_viewsB\x15\n" +
	"\x13_applications_count\"\xae\x05\n" +
	"\x14CreateVacancyRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\"\n" +
	"\frequirements\x18\x03 \x01(\tR\frequirements\x12\x1e\n" +
	"\n" +
	"conditions\x18\x04 \x01(\tR\n" +
	"conditions\x12\"\n" +
	"\n" +
	"salary_min\x18\x05 \x01(\x04H\x01R\tsalaryMin\x88\x01\x01\x12\"\n" +
	"\n" +
	"salary_max\x18\x06 \x01(\x04H\x02R\tsalaryMax\x88\x01\x01\x12-\n" +
	"\bcurrency\x18\a \x01(\x0e2\x11.vacancy.CurrencyR\bcurrency\x12\x17\n" +
	"\x04city\x18\b \x01(\tH\x03R\x04city\x88\x01\x01\x12\x19\n" +
	"\x05metro\x18\t \x01(\tH\x04R\x05metro\x88\x01\x01\x124\n" +
	"\vremote_type\x18\n" +
	" \x01(\x0e2\x13.vacancy.RemoteTypeR\n" +
	"remoteType\x12.\n" +
	"\ttime_type\x18\v \x01(\x0e2\x11.vacancy.TimeTypeR\btimeType\x12*\n" +
	"\x0eexperience_min\x18\f \x01(\rH\x05R\rexperienceMin\x88\x01\x01\x12*\n" +
	"\x0eexperience_max\x18\r \x01(\rH\x06R\rexperienceMax\x88\x01\x01\x12\x12\n" +
	"\x04tags\x18\x0e \x03(\tR\x04tags\x121\n" +
	"\tuser_info\x18\x0f \x01(\v2\x14.common.FullUserInfoR\buserInfoB\x0e\n" +
	"\f_descriptionB\r\n" +
	"\v_salary_minB\r\n" +
	"\v_salary_maxB\a\n" +
	"\x05_cityB\b\n" +
	"\x06_metroB\x11\n" +
	"\x0f_experience_minB\x11\n" +
	"\x0f_experience_max\"\xdd\x06\n" +
	"\x14UpdateVacancyRequest\x12\x1d\n" +
	"\n" +
	"vacancy_id\x18\x01 \x01(\x04R\tvacancyId\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12'\n" +
	"\frequirements\x18\x04 \x01(\tH\x02R\frequirements\x88\x01\x01\x12#\n" +
	"\n" +
	"conditions\x18\x05 \x01(\tH\x03R\n" +
	"conditions\x88\x01\x01\x12\"\n" +
	"\n" +
	"salary_min\x18\x06 \x01(\x04H\x04R\tsalaryMin\x88\x01\x01\x12\"\n" +
	"\n" +
	"salary_max\x18\a \x01(\x04H\x05R\tsalaryMax\x88\x01\x01\x122\n" +
	"\bcurrency\x18\b \x01(\x0e2\x11.vacancy.CurrencyH\x06R\bcurrency\x88\x01\x01\x12\x17\n" +
	"\x04city\x18\t \x01(\tH\aR\x04city\x88\x01\x01\x12\x19\n" +
	"\x05metro\x18\n" +
	" \x01(\tH\bR\x05metro\x88\x01\x01\x129\n" +
	"\vremote_type\x18\v \x01(\x0e2\x13.vacancy.RemoteTypeH\tR\n" +
	"remoteType\x88\x01\x01\x123\n" +
	"\ttime_type\x18\f \x01(\x0e2\x11.vacancy.TimeTypeH\n" +
	"R\btimeType\x88\x01\x01\x12*\n" +
	"\x0eexperience_min\x18\r \x01(\rH\vR\rexperienceMin\x88\x01\x01\x12*\n" +
	"\x0eexperience_max\x18\x0e \x01(\rH\fR\rexperienceMax\x88\x01\x01\x12\x12\n" +
	"\x04tags\x18\x18 \x03(\tR\x04tags\x12\x1f\n" +
	"\vupdate_tags\x18\x1a \x01(\bR\n" +
	"updateTags\x12-\n" +
	"\tuser_info\x18\x19 \x01(\v2\x10.common.UserInfoR\buserInfoB\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_descriptionB\x0f\n" +
	"\r_requirementsB\r\n" +
	"\v_conditionsB\r\n" +
	"\v_salary_minB\r\n" +
	"\v_salary_maxB\v\n" +
	"\t_currencyB\a\n" +
	"\x05_cityB\b\n" +
	"\x06_metroB\x0e\n" +
	"\f_remote_typeB\f\n" +
	"\n" +
	"_time_typeB\x11\n" +
	"\x0f_experience_minB\x11\n" +
	"\x0f_experience_max\"d\n" +
	"\x14DeleteVacancyRequest\x12\x1d\n" +
	"\n" +
	"vacancy_id\x18\x01 \x01(\x04R\tvacancyId\x12-\n" +
	"\tuser_info\x18\x02 \x01(\v2\x10.common.UserInfoR\buserInfo\"y\n" +
	"\x16FindVacancyByIDRequest\x12\x1d\n" +
	"\n" +
	"vacancy_id\x18\x01 \x01(\x04R\tvacancyId\x122\n" +
	"\tuser_info\x18\x02 \x01(\v2\x10.common.UserInfoH\x00R\buserInfo\x88\x01\x01B\f\n" +
	"\n" +
	"_user_info\"\xdd\x01\n" +
	"\x18FindVacancyByTagsRequest\x12\x12\n" +
	"\x04tags\x18\x01 \x03(\tR\x04tags\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\rR\x06offset\x120\n" +
	"\border_by\x18\x04 \x01(\x0e2\x10.vacancy.OrderByH\x00R\aorderBy\x88\x01\x01\x122\n" +
	"\tuser_info\x18\x05 \x01(\v2\x10.common.UserInfoH\x01R\buserInfo\x88\x01\x01B\v\n" +
	"\t_order_byB\f\n" +
	"\n" +
	"_user_info\"m\n" +
	"\tVacancies\x122\n" +
	"\tvacancies\x18\x01 \x03(\v2\x14.vacancy.VacancyInfoR\tvacancies\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\rR\x06offset\"\xdb\x01\n" +
	"\x1cFindVacanciesByAuthorRequest\x12\x1f\n" +
	"\vauthor_name\x18\x01 \x01(\tR\n" +
	"authorName\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\rR\x06offset\x120\n" +
	"\border_by\x18\x04 \x01(\x0e2\x10.vacancy.OrderByH\x00R\aorderBy\x88\x01\x01\x12-\n" +
	"\tuser_info\x18\x05 \x01(\v2\x10.common.UserInfoR\buserInfoB\v\n" +
	"\t_order_by\"\xbc\x01\n" +
	"\x1eFindVacanciesByAuthorIDRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\rR\x06offset\x120\n" +
	"\border_by\x18\x03 \x01(\x0e2\x10.vacancy.OrderByH\x00R\aorderBy\x88\x01\x01\x12-\n" +
	"\tuser_info\x18\x04 \x01(\v2\x10.common.UserInfoR\buserInfoB\v\n" +
	"\t_order_by\"\xcf\x01\n" +
	"\x1bFindVacanciesByTitleRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\rR\x06offset\x120\n" +
	"\border_by\x18\x04 \x01(\x0e2\x10.vacancy.OrderByH\x00R\aorderBy\x88\x01\x01\x12-\n" +
	"\tuser_info\x18\x05 \x01(\v2\x10.common.UserInfoR\buserInfoB\v\n" +
	"\t_order_by\"\xc6\x01\n" +
	"\x17SetVacancyStatusRequest\x12\x1d\n" +
	"\n" +
	"vacancy_id\x18\x01 \x01(\x04R\tvacancyId\x12.\n" +
	"\x06status\x18\x02 \x01(\x0e2\x16.vacancy.VacancyStatusR\x06status\x12-\n" +
	"\x12moderator_comments\x18\x03 \x01(\tR\x11moderatorComments\x12-\n" +
	"\tuser_info\x18\x04 \x01(\v2\x10.common.UserInfoR\buserInfo*9\n" +
	"\n" +
	"RemoteType\x12\n" +
	"\n" +
	"\x06OFFICE\x10\x00\x12\n" +
	"\n" +
	"\x06REMOTE\x10\x01\x12\n" +
	"\n" +
	"\x06HYBRID\x10\x02\x12\a\n" +
	"\x03ANY\x10\x03*\x1e\n" +
	"\bTimeType\x12\b\n" +
	"\x04FULL\x10\x00\x12\b\n" +
	"\x04PART\x10\x01*%\n" +
	"\bCurrency\x12\a\n" +
	"\x03RUB\x10\x00\x12\a\n" +
	"\x03USD\x10\x01\x12\a\n" +
	"\x03EUR\x10\x02*G\n" +
	"\rVacancyStatus\x12\x0e\n" +
	"\n" +
	"MODERATING\x10\x00\x12\r\n" +
	"\tPUBLISHED\x10\x01\x12\n" +
	"\n" +
	"\x06CLOSED\x10\x02\x12\v\n" +
	"\aDELETED\x10\x03*G\n" +
	"\x0eResponseStatus\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\n" +
	"\n" +
	"\x06FAILED\x10\x01\x12\r\n" +
	"\tNOT_FOUND\x10\x02\x12\r\n" +
	"\tFORBIDDEN\x10\x03*K\n" +
	"\aOrderBy\x12\b\n" +
	"\x04DATE\x10\x00\x12\t\n" +
	"\x05VIEWS\x10\x01\x12\x14\n" +
	"\x10APPLICATIONS_ASC\x10\x02\x12\x15\n" +
	"\x11APPLICATIONS_DESC\x10\x032\xe7\x05\n" +
	"\aVacancy\x12.\n" +
	"\x06Health\x12\r.common.Empty\x1a\x15.common.ServiceStatus\x12D\n" +
	"\rCreateVacancy\x12\x1d.vacancy.CreateVacancyRequest\x1a\x14.vacancy.VacancyInfo\x12H\n" +
	"\x0fFindVacancyByID\x12\x1f.vacancy.FindVacancyByIDRequest\x1a\x14.vacancy.VacancyInfo\x12L\n" +
	"\x13FindVacanciesByTags\x12!.vacancy.FindVacancyByTagsRequest\x1a\x12.vacancy.Vacancies\x12R\n" +
	"\x15FindVacanciesByAuthor\x12%.vacancy.FindVacanciesByAuthorRequest\x1a\x12.vacancy.Vacancies\x12V\n" +
	"\x17FindVacanciesByAuthorID\x12'.vacancy.FindVacanciesByAuthorIDRequest\x1a\x12.vacancy.Vacancies\x12P\n" +
	"\x14FindVacanciesByTitle\x12$.vacancy.FindVacanciesByTitleRequest\x1a\x12.vacancy.Vacancies\x12D\n" +
	"\rUpdateVacancy\x12\x1d.vacancy.UpdateVacancyRequest\x1a\x14.vacancy.VacancyInfo\x12A\n" +
	"\rDeleteVacancy\x12\x1d.vacancy.DeleteVacancyRequest\x1a\x11.vacancy.Response\x12G\n" +
	"\x10SetVacancyStatus\x12 .vacancy.SetVacancyStatusRequest\x1a\x11.vacancy.ResponseB\x11Z\x0fpkg/vacancy_apib\x06proto3"

var (
	file_protos_vacancy_proto_rawDescOnce sync.Once
	file_protos_vacancy_proto_rawDescData []byte
)

func file_protos_vacancy_proto_rawDescGZIP() []byte {
	file_protos_vacancy_proto_rawDescOnce.Do(func() {
		file_protos_vacancy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_vacancy_proto_rawDesc), len(file_protos_vacancy_proto_rawDesc)))
	})
	return file_protos_vacancy_proto_rawDescData
}

var file_protos_vacancy_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_protos_vacancy_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_protos_vacancy_proto_goTypes = []any{
	(RemoteType)(0),                        // 0: vacancy.RemoteType
	(TimeType)(0),                          // 1: vacancy.TimeType
	(Currency)(0),                          // 2: vacancy.Currency
	(VacancyStatus)(0),                     // 3: vacancy.VacancyStatus
	(ResponseStatus)(0),                    // 4: vacancy.ResponseStatus
	(OrderBy)(0),                           // 5: vacancy.OrderBy
	(*Response)(nil),                       // 6: vacancy.Response
	(*VacancyInfo)(nil),                    // 7: vacancy.VacancyInfo
	(*CreateVacancyRequest)(nil),           // 8: vacancy.CreateVacancyRequest
	(*UpdateVacancyRequest)(nil),           // 9: vacancy.UpdateVacancyRequest
	(*DeleteVacancyRequest)(nil),           // 10: vacancy.DeleteVacancyRequest
	(*FindVacancyByIDRequest)(nil),         // 11: vacancy.FindVacancyByIDRequest
	(*FindVacancyByTagsRequest)(nil),       // 12: vacancy.FindVacancyByTagsRequest
	(*Vacancies)(nil),                      // 13: vacancy.Vacancies
	(*FindVacanciesByAuthorRequest)(nil),   // 14: vacancy.FindVacanciesByAuthorRequest
	(*FindVacanciesByAuthorIDRequest)(nil), // 15: vacancy.FindVacanciesByAuthorIDRequest
	(*FindVacanciesByTitleRequest)(nil),    // 16: vacancy.FindVacanciesByTitleRequest
	(*SetVacancyStatusRequest)(nil),        // 17: vacancy.SetVacancyStatusRequest
	(*timestamppb.Timestamp)(nil),          // 18: google.protobuf.Timestamp
	(*common.FullUserInfo)(nil),            // 19: common.FullUserInfo
	(*common.UserInfo)(nil),                // 20: common.UserInfo
	(*common.Empty)(nil),                   // 21: common.Empty
	(*common.ServiceStatus)(nil),           // 22: common.ServiceStatus
}
var file_protos_vacancy_proto_depIdxs = []int32{
	4,  // 0: vacancy.Response.status:type_name -> vacancy.ResponseStatus
	2,  // 1: vacancy.VacancyInfo.currency:type_name -> vacancy.Currency
	0,  // 2: vacancy.VacancyInfo.remote_type:type_name -> vacancy.RemoteType
	1,  // 3: vacancy.VacancyInfo.time_type:type_name -> vacancy.TimeType
	18, // 4: vacancy.VacancyInfo.created_at:type_name -> google.protobuf.Timestamp
	18, // 5: vacancy.VacancyInfo.updated_at:type_name -> google.protobuf.Timestamp
	18, // 6: vacancy.VacancyInfo.published_at:type_name -> google.protobuf.Timestamp
	18, // 7: vacancy.VacancyInfo.closed_at:type_name -> google.protobuf.Timestamp
	3,  // 8: vacancy.VacancyInfo.status:type_name -> vacancy.VacancyStatus
	18, // 9: vacancy.VacancyInfo.moderated_time:type_name -> google.protobuf.Timestamp
	2,  // 10: vacancy.CreateVacancyRequest.currency:type_name -> vacancy.Currency
	0,  // 11: vacancy.CreateVacancyRequest.remote_type:type_name -> vacancy.RemoteType
	1,  // 12: vacancy.CreateVacancyRequest.time_type:type_name -> vacancy.TimeType
	19, // 13: vacancy.CreateVacancyRequest.user_info:type_name -> common.FullUserInfo
	2,  // 14: vacancy.UpdateVacancyRequest.currency:type_name -> vacancy.Currency
	0,  // 15: vacancy.UpdateVacancyRequest.remote_type:type_name -> vacancy.RemoteType
	1,  // 16: vacancy.UpdateVacancyRequest.time_type:type_name -> vacancy.TimeType
	20, // 17: vacancy.UpdateVacancyRequest.user_info:type_name -> common.UserInfo
	20, // 18: vacancy.DeleteVacancyRequest.user_info:type_name -> common.UserInfo
	20, // 19: vacancy.FindVacancyByIDRequest.user_info:type_name -> common.UserInfo
	5,  // 20: vacancy.FindVacancyByTagsRequest.order_by:type_name -> vacancy.OrderBy
	20, // 21: vacancy.FindVacancyByTagsRequest.user_info:type_name -> common.UserInfo
	7,  // 22: vacancy.Vacancies.vacancies:type_name -> vacancy.VacancyInfo
	5,  // 23: vacancy.FindVacanciesByAuthorRequest.order_by:type_name -> vacancy.OrderBy
	20, // 24: vacancy.FindVacanciesByAuthorRequest.user_info:type_name -> common.UserInfo
	5,  // 25: vacancy.FindVacanciesByAuthorIDRequest.order_by:type_name -> vacancy.OrderBy
	20, // 26: vacancy.FindVacanciesByAuthorIDRequest.user_info:type_name -> common.UserInfo
	5,  // 27: vacancy.FindVacanciesByTitleRequest.order_by:type_name -> vacancy.OrderBy
	20, // 28: vacancy.FindVacanciesByTitleRequest.user_info:type_name -> common.UserInfo
	3,  // 29: vacancy.SetVacancyStatusRequest.status:type_name -> vacancy.VacancyStatus
	20, // 30: vacancy.SetVacancyStatusRequest.user_info:type_name -> common.UserInfo
	21, // 31: vacancy.Vacancy.Health:input_type -> common.Empty
	8,  // 32: vacancy.Vacancy.CreateVacancy:input_type -> vacancy.CreateVacancyRequest
	11, // 33: vacancy.Vacancy.FindVacancyByID:input_type -> vacancy.FindVacancyByIDRequest
	12, // 34: vacancy.Vacancy.FindVacanciesByTags:input_type -> vacancy.FindVacancyByTagsRequest
	14, // 35: vacancy.Vacancy.FindVacanciesByAuthor:input_type -> vacancy.FindVacanciesByAuthorRequest
	15, // 36: vacancy.Vacancy.FindVacanciesByAuthorID:input_type -> vacancy.FindVacanciesByAuthorIDRequest
	16, // 37: vacancy.Vacancy.FindVacanciesByTitle:input_type -> vacancy.FindVacanciesByTitleRequest
	9,  // 38: vacancy.Vacancy.UpdateVacancy:input_type -> vacancy.UpdateVacancyRequest
	10, // 39: vacancy.Vacancy.DeleteVacancy:input_type -> vacancy.DeleteVacancyRequest
	17, // 40: vacancy.Vacancy.SetVacancyStatus:input_type -> vacancy.SetVacancyStatusRequest
	22, // 41: vacancy.Vacancy.Health:output_type -> common.ServiceStatus
	7,  // 42: vacancy.Vacancy.CreateVacancy:output_type -> vacancy.VacancyInfo
	7,  // 43: vacancy.Vacancy.FindVacancyByID:output_type -> vacancy.VacancyInfo
	13, // 44: vacancy.Vacancy.FindVacanciesByTags:output_type -> vacancy.Vacancies
	13, // 45: vacancy.Vacancy.FindVacanciesByAuthor:output_type -> vacancy.Vacancies
	13, // 46: vacancy.Vacancy.FindVacanciesByAuthorID:output_type -> vacancy.Vacancies
	13, // 47: vacancy.Vacancy.FindVacanciesByTitle:output_type -> vacancy.Vacancies
	7,  // 48: vacancy.Vacancy.UpdateVacancy:output_type -> vacancy.VacancyInfo
	6,  // 49: vacancy.Vacancy.DeleteVacancy:output_type -> vacancy.Response
	6,  // 50: vacancy.Vacancy.SetVacancyStatus:output_type -> vacancy.Response
	41, // [41:51] is the sub-list for method output_type
	31, // [31:41] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_protos_vacancy_proto_init() }
func file_protos_vacancy_proto_init() {
	if File_protos_vacancy_proto != nil {
		return
	}
	file_protos_vacancy_proto_msgTypes[1].OneofWrappers = []any{}
	file_protos_vacancy_proto_msgTypes[2].OneofWrappers = []any{}
	file_protos_vacancy_proto_msgTypes[3].OneofWrappers = []any{}
	file_protos_vacancy_proto_msgTypes[5].OneofWrappers = []any{}
	file_protos_vacancy_proto_msgTypes[6].OneofWrappers = []any{}
	file_protos_vacancy_proto_msgTypes[8].OneofWrappers = []any{}
	file_protos_vacancy_proto_msgTypes[9].OneofWrappers = []any{}
	file_protos_vacancy_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_vacancy_proto_rawDesc), len(file_protos_vacancy_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_vacancy_proto_goTypes,
		DependencyIndexes: file_protos_vacancy_proto_depIdxs,
		EnumInfos:         file_protos_vacancy_proto_enumTypes,
		MessageInfos:      file_protos_vacancy_proto_msgTypes,
	}.Build()
	File_protos_vacancy_proto = out.File
	file_protos_vacancy_proto_goTypes = nil
	file_protos_vacancy_proto_depIdxs = nil
}
