// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: protos/vacancy.proto

package vacancy_api

import (
	context "context"
	common "github.com/IvanDrf/work-hunter/pkg/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Vacancy_Health_FullMethodName                  = "/vacancy.Vacancy/Health"
	Vacancy_CreateVacancy_FullMethodName           = "/vacancy.Vacancy/CreateVacancy"
	Vacancy_FindVacancyByID_FullMethodName         = "/vacancy.Vacancy/FindVacancyByID"
	Vacancy_FindVacanciesByTags_FullMethodName     = "/vacancy.Vacancy/FindVacanciesByTags"
	Vacancy_FindVacanciesByAuthor_FullMethodName   = "/vacancy.Vacancy/FindVacanciesByAuthor"
	Vacancy_FindVacanciesByAuthorID_FullMethodName = "/vacancy.Vacancy/FindVacanciesByAuthorID"
	Vacancy_FindVacanciesByTitle_FullMethodName    = "/vacancy.Vacancy/FindVacanciesByTitle"
	Vacancy_UpdateVacancy_FullMethodName           = "/vacancy.Vacancy/UpdateVacancy"
	Vacancy_DeleteVacancy_FullMethodName           = "/vacancy.Vacancy/DeleteVacancy"
	Vacancy_SetVacancyStatus_FullMethodName        = "/vacancy.Vacancy/SetVacancyStatus"
)

// VacancyClient is the client API for Vacancy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Vacancy service
type VacancyClient interface {
	// check service health
	Health(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*common.ServiceStatus, error)
	// Create vacancy, returns vacancy_id if success
	CreateVacancy(ctx context.Context, in *CreateVacancyRequest, opts ...grpc.CallOption) (*VacancyInfo, error)
	// Find vacancy by it's id
	// If vacancy has status - MODERATING only moderator or user who created this vacancy can see it
	FindVacancyByID(ctx context.Context, in *FindVacancyByIDRequest, opts ...grpc.CallOption) (*VacancyInfo, error)
	// Find vacancy by tags
	// If vacancy has status - MODERATING only moderator or user who created this vacancy can see it
	FindVacanciesByTags(ctx context.Context, in *FindVacancyByTagsRequest, opts ...grpc.CallOption) (*Vacancies, error)
	// Find vacancies by author name
	// If vacancy has status - MODERATING only moderator or user who created this vacancy can see it
	FindVacanciesByAuthor(ctx context.Context, in *FindVacanciesByAuthorRequest, opts ...grpc.CallOption) (*Vacancies, error)
	// Find vacancies by author ID
	// Main usage - 'my vacancies'
	FindVacanciesByAuthorID(ctx context.Context, in *FindVacanciesByAuthorIDRequest, opts ...grpc.CallOption) (*Vacancies, error)
	// Find vacancies by title
	// If vacancy has status - MODERATING only moderator can see this
	FindVacanciesByTitle(ctx context.Context, in *FindVacanciesByTitleRequest, opts ...grpc.CallOption) (*Vacancies, error)
	// Update vacancy information
	UpdateVacancy(ctx context.Context, in *UpdateVacancyRequest, opts ...grpc.CallOption) (*VacancyInfo, error)
	// Delete vacancy by user who created it or by moderator
	DeleteVacancy(ctx context.Context, in *DeleteVacancyRequest, opts ...grpc.CallOption) (*Response, error)
	// Set vacancy status by moderator
	// For example, from MODERATING to PUBLISHED
	SetVacancyStatus(ctx context.Context, in *SetVacancyStatusRequest, opts ...grpc.CallOption) (*Response, error)
}

type vacancyClient struct {
	cc grpc.ClientConnInterface
}

func NewVacancyClient(cc grpc.ClientConnInterface) VacancyClient {
	return &vacancyClient{cc}
}

func (c *vacancyClient) Health(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*common.ServiceStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.ServiceStatus)
	err := c.cc.Invoke(ctx, Vacancy_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vacancyClient) CreateVacancy(ctx context.Context, in *CreateVacancyRequest, opts ...grpc.CallOption) (*VacancyInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VacancyInfo)
	err := c.cc.Invoke(ctx, Vacancy_CreateVacancy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vacancyClient) FindVacancyByID(ctx context.Context, in *FindVacancyByIDRequest, opts ...grpc.CallOption) (*VacancyInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VacancyInfo)
	err := c.cc.Invoke(ctx, Vacancy_FindVacancyByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vacancyClient) FindVacanciesByTags(ctx context.Context, in *FindVacancyByTagsRequest, opts ...grpc.CallOption) (*Vacancies, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Vacancies)
	err := c.cc.Invoke(ctx, Vacancy_FindVacanciesByTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vacancyClient) FindVacanciesByAuthor(ctx context.Context, in *FindVacanciesByAuthorRequest, opts ...grpc.CallOption) (*Vacancies, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Vacancies)
	err := c.cc.Invoke(ctx, Vacancy_FindVacanciesByAuthor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vacancyClient) FindVacanciesByAuthorID(ctx context.Context, in *FindVacanciesByAuthorIDRequest, opts ...grpc.CallOption) (*Vacancies, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Vacancies)
	err := c.cc.Invoke(ctx, Vacancy_FindVacanciesByAuthorID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vacancyClient) FindVacanciesByTitle(ctx context.Context, in *FindVacanciesByTitleRequest, opts ...grpc.CallOption) (*Vacancies, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Vacancies)
	err := c.cc.Invoke(ctx, Vacancy_FindVacanciesByTitle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vacancyClient) UpdateVacancy(ctx context.Context, in *UpdateVacancyRequest, opts ...grpc.CallOption) (*VacancyInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VacancyInfo)
	err := c.cc.Invoke(ctx, Vacancy_UpdateVacancy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vacancyClient) DeleteVacancy(ctx context.Context, in *DeleteVacancyRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, Vacancy_DeleteVacancy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vacancyClient) SetVacancyStatus(ctx context.Context, in *SetVacancyStatusRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, Vacancy_SetVacancyStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VacancyServer is the server API for Vacancy service.
// All implementations must embed UnimplementedVacancyServer
// for forward compatibility.
//
// Vacancy service
type VacancyServer interface {
	// check service health
	Health(context.Context, *common.Empty) (*common.ServiceStatus, error)
	// Create vacancy, returns vacancy_id if success
	CreateVacancy(context.Context, *CreateVacancyRequest) (*VacancyInfo, error)
	// Find vacancy by it's id
	// If vacancy has status - MODERATING only moderator or user who created this vacancy can see it
	FindVacancyByID(context.Context, *FindVacancyByIDRequest) (*VacancyInfo, error)
	// Find vacancy by tags
	// If vacancy has status - MODERATING only moderator or user who created this vacancy can see it
	FindVacanciesByTags(context.Context, *FindVacancyByTagsRequest) (*Vacancies, error)
	// Find vacancies by author name
	// If vacancy has status - MODERATING only moderator or user who created this vacancy can see it
	FindVacanciesByAuthor(context.Context, *FindVacanciesByAuthorRequest) (*Vacancies, error)
	// Find vacancies by author ID
	// Main usage - 'my vacancies'
	FindVacanciesByAuthorID(context.Context, *FindVacanciesByAuthorIDRequest) (*Vacancies, error)
	// Find vacancies by title
	// If vacancy has status - MODERATING only moderator can see this
	FindVacanciesByTitle(context.Context, *FindVacanciesByTitleRequest) (*Vacancies, error)
	// Update vacancy information
	UpdateVacancy(context.Context, *UpdateVacancyRequest) (*VacancyInfo, error)
	// Delete vacancy by user who created it or by moderator
	DeleteVacancy(context.Context, *DeleteVacancyRequest) (*Response, error)
	// Set vacancy status by moderator
	// For example, from MODERATING to PUBLISHED
	SetVacancyStatus(context.Context, *SetVacancyStatusRequest) (*Response, error)
	mustEmbedUnimplementedVacancyServer()
}

// UnimplementedVacancyServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVacancyServer struct{}

func (UnimplementedVacancyServer) Health(context.Context, *common.Empty) (*common.ServiceStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedVacancyServer) CreateVacancy(context.Context, *CreateVacancyRequest) (*VacancyInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateVacancy not implemented")
}
func (UnimplementedVacancyServer) FindVacancyByID(context.Context, *FindVacancyByIDRequest) (*VacancyInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method FindVacancyByID not implemented")
}
func (UnimplementedVacancyServer) FindVacanciesByTags(context.Context, *FindVacancyByTagsRequest) (*Vacancies, error) {
	return nil, status.Error(codes.Unimplemented, "method FindVacanciesByTags not implemented")
}
func (UnimplementedVacancyServer) FindVacanciesByAuthor(context.Context, *FindVacanciesByAuthorRequest) (*Vacancies, error) {
	return nil, status.Error(codes.Unimplemented, "method FindVacanciesByAuthor not implemented")
}
func (UnimplementedVacancyServer) FindVacanciesByAuthorID(context.Context, *FindVacanciesByAuthorIDRequest) (*Vacancies, error) {
	return nil, status.Error(codes.Unimplemented, "method FindVacanciesByAuthorID not implemented")
}
func (UnimplementedVacancyServer) FindVacanciesByTitle(context.Context, *FindVacanciesByTitleRequest) (*Vacancies, error) {
	return nil, status.Error(codes.Unimplemented, "method FindVacanciesByTitle not implemented")
}
func (UnimplementedVacancyServer) UpdateVacancy(context.Context, *UpdateVacancyRequest) (*VacancyInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateVacancy not implemented")
}
func (UnimplementedVacancyServer) DeleteVacancy(context.Context, *DeleteVacancyRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteVacancy not implemented")
}
func (UnimplementedVacancyServer) SetVacancyStatus(context.Context, *SetVacancyStatusRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method SetVacancyStatus not implemented")
}
func (UnimplementedVacancyServer) mustEmbedUnimplementedVacancyServer() {}
func (UnimplementedVacancyServer) testEmbeddedByValue()                 {}

// UnsafeVacancyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VacancyServer will
// result in compilation errors.
type UnsafeVacancyServer interface {
	mustEmbedUnimplementedVacancyServer()
}

func RegisterVacancyServer(s grpc.ServiceRegistrar, srv VacancyServer) {
	// If the following call panics, it indicates UnimplementedVacancyServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Vacancy_ServiceDesc, srv)
}

func _Vacancy_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VacancyServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vacancy_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VacancyServer).Health(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vacancy_CreateVacancy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVacancyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VacancyServer).CreateVacancy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vacancy_CreateVacancy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VacancyServer).CreateVacancy(ctx, req.(*CreateVacancyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vacancy_FindVacancyByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindVacancyByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VacancyServer).FindVacancyByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vacancy_FindVacancyByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VacancyServer).FindVacancyByID(ctx, req.(*FindVacancyByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vacancy_FindVacanciesByTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindVacancyByTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VacancyServer).FindVacanciesByTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vacancy_FindVacanciesByTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VacancyServer).FindVacanciesByTags(ctx, req.(*FindVacancyByTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vacancy_FindVacanciesByAuthor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindVacanciesByAuthorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VacancyServer).FindVacanciesByAuthor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vacancy_FindVacanciesByAuthor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VacancyServer).FindVacanciesByAuthor(ctx, req.(*FindVacanciesByAuthorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vacancy_FindVacanciesByAuthorID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindVacanciesByAuthorIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VacancyServer).FindVacanciesByAuthorID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vacancy_FindVacanciesByAuthorID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VacancyServer).FindVacanciesByAuthorID(ctx, req.(*FindVacanciesByAuthorIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vacancy_FindVacanciesByTitle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindVacanciesByTitleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VacancyServer).FindVacanciesByTitle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vacancy_FindVacanciesByTitle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VacancyServer).FindVacanciesByTitle(ctx, req.(*FindVacanciesByTitleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vacancy_UpdateVacancy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateVacancyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VacancyServer).UpdateVacancy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vacancy_UpdateVacancy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VacancyServer).UpdateVacancy(ctx, req.(*UpdateVacancyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vacancy_DeleteVacancy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVacancyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VacancyServer).DeleteVacancy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vacancy_DeleteVacancy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VacancyServer).DeleteVacancy(ctx, req.(*DeleteVacancyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vacancy_SetVacancyStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetVacancyStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VacancyServer).SetVacancyStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vacancy_SetVacancyStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VacancyServer).SetVacancyStatus(ctx, req.(*SetVacancyStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Vacancy_ServiceDesc is the grpc.ServiceDesc for Vacancy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Vacancy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vacancy.Vacancy",
	HandlerType: (*VacancyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _Vacancy_Health_Handler,
		},
		{
			MethodName: "CreateVacancy",
			Handler:    _Vacancy_CreateVacancy_Handler,
		},
		{
			MethodName: "FindVacancyByID",
			Handler:    _Vacancy_FindVacancyByID_Handler,
		},
		{
			MethodName: "FindVacanciesByTags",
			Handler:    _Vacancy_FindVacanciesByTags_Handler,
		},
		{
			MethodName: "FindVacanciesByAuthor",
			Handler:    _Vacancy_FindVacanciesByAuthor_Handler,
		},
		{
			MethodName: "FindVacanciesByAuthorID",
			Handler:    _Vacancy_FindVacanciesByAuthorID_Handler,
		},
		{
			MethodName: "FindVacanciesByTitle",
			Handler:    _Vacancy_FindVacanciesByTitle_Handler,
		},
		{
			MethodName: "UpdateVacancy",
			Handler:    _Vacancy_UpdateVacancy_Handler,
		},
		{
			MethodName: "DeleteVacancy",
			Handler:    _Vacancy_DeleteVacancy_Handler,
		},
		{
			MethodName: "SetVacancyStatus",
			Handler:    _Vacancy_SetVacancyStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/vacancy.proto",
}
