# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import vacancy_pb2 as vacancy__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in vacancy_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VacancyStub(object):
    """Vacancy service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateVacancy = channel.unary_unary(
            '/vacancy.Vacancy/CreateVacancy',
            request_serializer=vacancy__pb2.CreateVacancyRequest.SerializeToString,
            response_deserializer=vacancy__pb2.CreateVacancyResponse.FromString,
            _registered_method=True)
        self.FindVacancyByID = channel.unary_unary(
            '/vacancy.Vacancy/FindVacancyByID',
            request_serializer=vacancy__pb2.FindVacancyByIDRequest.SerializeToString,
            response_deserializer=vacancy__pb2.VacancyInfo.FromString,
            _registered_method=True)
        self.FindVacanciesByTags = channel.unary_unary(
            '/vacancy.Vacancy/FindVacanciesByTags',
            request_serializer=vacancy__pb2.FindVacancyByTagsRequest.SerializeToString,
            response_deserializer=vacancy__pb2.Vacancies.FromString,
            _registered_method=True)
        self.FindVacanciesByAuthor = channel.unary_unary(
            '/vacancy.Vacancy/FindVacanciesByAuthor',
            request_serializer=vacancy__pb2.FindVacanciesByAuthorRequest.SerializeToString,
            response_deserializer=vacancy__pb2.Vacancies.FromString,
            _registered_method=True)
        self.UpdateVacancy = channel.unary_unary(
            '/vacancy.Vacancy/UpdateVacancy',
            request_serializer=vacancy__pb2.UpdateVacancyRequest.SerializeToString,
            response_deserializer=vacancy__pb2.Response.FromString,
            _registered_method=True)
        self.DeleteVacancy = channel.unary_unary(
            '/vacancy.Vacancy/DeleteVacancy',
            request_serializer=vacancy__pb2.DeleteVacancyRequest.SerializeToString,
            response_deserializer=vacancy__pb2.Response.FromString,
            _registered_method=True)
        self.SetVacancyStatus = channel.unary_unary(
            '/vacancy.Vacancy/SetVacancyStatus',
            request_serializer=vacancy__pb2.SetVacancyStatusRequest.SerializeToString,
            response_deserializer=vacancy__pb2.Response.FromString,
            _registered_method=True)


class VacancyServicer(object):
    """Vacancy service
    """

    def CreateVacancy(self, request, context):
        """Create vacancy, returns vacancy_id if success
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindVacancyByID(self, request, context):
        """Find vacancy by it's id
        If vacancy has status - MODERATING only moderator or user who created this vacancy can see it
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindVacanciesByTags(self, request, context):
        """Find vacancy by tags
        If vacancy has status - MODERATING only moderator or user who created this vacancy can see it 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindVacanciesByAuthor(self, request, context):
        """Find vacancies by author name
        If vacancy has status - MODERATING only moderator or user who created this vacancy can see it  
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateVacancy(self, request, context):
        """Update vacancy information
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteVacancy(self, request, context):
        """Delete vacancy by user who created it or by moderator
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetVacancyStatus(self, request, context):
        """Set vacancy status by moderator
        For example, from MODERATING to PUBLISHED
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VacancyServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'CreateVacancy': grpc.unary_unary_rpc_method_handler(
            servicer.CreateVacancy,
            request_deserializer=vacancy__pb2.CreateVacancyRequest.FromString,
            response_serializer=vacancy__pb2.CreateVacancyResponse.SerializeToString,
        ),
        'FindVacancyByID': grpc.unary_unary_rpc_method_handler(
            servicer.FindVacancyByID,
            request_deserializer=vacancy__pb2.FindVacancyByIDRequest.FromString,
            response_serializer=vacancy__pb2.VacancyInfo.SerializeToString,
        ),
        'FindVacanciesByTags': grpc.unary_unary_rpc_method_handler(
            servicer.FindVacanciesByTags,
            request_deserializer=vacancy__pb2.FindVacancyByTagsRequest.FromString,
            response_serializer=vacancy__pb2.Vacancies.SerializeToString,
        ),
        'FindVacanciesByAuthor': grpc.unary_unary_rpc_method_handler(
            servicer.FindVacanciesByAuthor,
            request_deserializer=vacancy__pb2.FindVacanciesByAuthorRequest.FromString,
            response_serializer=vacancy__pb2.Vacancies.SerializeToString,
        ),
        'UpdateVacancy': grpc.unary_unary_rpc_method_handler(
            servicer.UpdateVacancy,
            request_deserializer=vacancy__pb2.UpdateVacancyRequest.FromString,
            response_serializer=vacancy__pb2.Response.SerializeToString,
        ),
        'DeleteVacancy': grpc.unary_unary_rpc_method_handler(
            servicer.DeleteVacancy,
            request_deserializer=vacancy__pb2.DeleteVacancyRequest.FromString,
            response_serializer=vacancy__pb2.Response.SerializeToString,
        ),
        'SetVacancyStatus': grpc.unary_unary_rpc_method_handler(
            servicer.SetVacancyStatus,
            request_deserializer=vacancy__pb2.SetVacancyStatusRequest.FromString,
            response_serializer=vacancy__pb2.Response.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'vacancy.Vacancy', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vacancy.Vacancy', rpc_method_handlers)

 # This class is part of an EXPERIMENTAL API.


class Vacancy(object):
    """Vacancy service
    """

    @staticmethod
    def CreateVacancy(request,
                      target,
                      options=(),
                      channel_credentials=None,
                      call_credentials=None,
                      insecure=False,
                      compression=None,
                      wait_for_ready=None,
                      timeout=None,
                      metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vacancy.Vacancy/CreateVacancy',
            vacancy__pb2.CreateVacancyRequest.SerializeToString,
            vacancy__pb2.CreateVacancyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindVacancyByID(request,
                        target,
                        options=(),
                        channel_credentials=None,
                        call_credentials=None,
                        insecure=False,
                        compression=None,
                        wait_for_ready=None,
                        timeout=None,
                        metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vacancy.Vacancy/FindVacancyByID',
            vacancy__pb2.FindVacancyByIDRequest.SerializeToString,
            vacancy__pb2.VacancyInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindVacanciesByTags(request,
                            target,
                            options=(),
                            channel_credentials=None,
                            call_credentials=None,
                            insecure=False,
                            compression=None,
                            wait_for_ready=None,
                            timeout=None,
                            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vacancy.Vacancy/FindVacanciesByTags',
            vacancy__pb2.FindVacancyByTagsRequest.SerializeToString,
            vacancy__pb2.Vacancies.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindVacanciesByAuthor(request,
                              target,
                              options=(),
                              channel_credentials=None,
                              call_credentials=None,
                              insecure=False,
                              compression=None,
                              wait_for_ready=None,
                              timeout=None,
                              metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vacancy.Vacancy/FindVacanciesByAuthor',
            vacancy__pb2.FindVacanciesByAuthorRequest.SerializeToString,
            vacancy__pb2.Vacancies.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateVacancy(request,
                      target,
                      options=(),
                      channel_credentials=None,
                      call_credentials=None,
                      insecure=False,
                      compression=None,
                      wait_for_ready=None,
                      timeout=None,
                      metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vacancy.Vacancy/UpdateVacancy',
            vacancy__pb2.UpdateVacancyRequest.SerializeToString,
            vacancy__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteVacancy(request,
                      target,
                      options=(),
                      channel_credentials=None,
                      call_credentials=None,
                      insecure=False,
                      compression=None,
                      wait_for_ready=None,
                      timeout=None,
                      metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vacancy.Vacancy/DeleteVacancy',
            vacancy__pb2.DeleteVacancyRequest.SerializeToString,
            vacancy__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetVacancyStatus(request,
                         target,
                         options=(),
                         channel_credentials=None,
                         call_credentials=None,
                         insecure=False,
                         compression=None,
                         wait_for_ready=None,
                         timeout=None,
                         metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vacancy.Vacancy/SetVacancyStatus',
            vacancy__pb2.SetVacancyStatusRequest.SerializeToString,
            vacancy__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
