# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from . import applications_pb2 as applications__pb2
from ..common import common_pb2 as common__pb2

GRPC_GENERATED_VERSION = "1.82.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in applications_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class ApplicationServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
            "/vacancy.ApplicationService/Health",
            request_serializer=common__pb2.Empty.SerializeToString,
            response_deserializer=common__pb2.ServiceStatus.FromString,
            _registered_method=True,
        )
        self.UpdateApplications = channel.unary_unary(
            "/vacancy.ApplicationService/UpdateApplications",
            request_serializer=applications__pb2.UpdateApplicationsRequest.SerializeToString,
            response_deserializer=common__pb2.Response.FromString,
            _registered_method=True,
        )
        self.FindVacanciesIDByUserID = channel.unary_unary(
            "/vacancy.ApplicationService/FindVacanciesIDByUserID",
            request_serializer=applications__pb2.FindVacanciesIDByUserIDRequest.SerializeToString,
            response_deserializer=applications__pb2.FindVacanciesIDByUserIDResponse.FromString,
            _registered_method=True,
        )


class ApplicationServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UpdateApplications(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def FindVacanciesIDByUserID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ApplicationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Health": grpc.unary_unary_rpc_method_handler(
            servicer.Health,
            request_deserializer=common__pb2.Empty.FromString,
            response_serializer=common__pb2.ServiceStatus.SerializeToString,
        ),
        "UpdateApplications": grpc.unary_unary_rpc_method_handler(
            servicer.UpdateApplications,
            request_deserializer=applications__pb2.UpdateApplicationsRequest.FromString,
            response_serializer=common__pb2.Response.SerializeToString,
        ),
        "FindVacanciesIDByUserID": grpc.unary_unary_rpc_method_handler(
            servicer.FindVacanciesIDByUserID,
            request_deserializer=applications__pb2.FindVacanciesIDByUserIDRequest.FromString,
            response_serializer=applications__pb2.FindVacanciesIDByUserIDResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("vacancy.ApplicationService", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("vacancy.ApplicationService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class ApplicationService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/vacancy.ApplicationService/Health",
            common__pb2.Empty.SerializeToString,
            common__pb2.ServiceStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UpdateApplications(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/vacancy.ApplicationService/UpdateApplications",
            applications__pb2.UpdateApplicationsRequest.SerializeToString,
            common__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def FindVacanciesIDByUserID(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/vacancy.ApplicationService/FindVacanciesIDByUserID",
            applications__pb2.FindVacanciesIDByUserIDRequest.SerializeToString,
            applications__pb2.FindVacanciesIDByUserIDResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
