# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: applications.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 7, 35, 0, "", "applications.proto")
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ..common import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x12\x61pplications.proto\x12\x07vacancy\x1a\x0c\x63ommon.proto"T\n\x19UpdateApplicationsRequest\x12\x12\n\nvacancy_id\x18\x01 \x01(\x04\x12#\n\tuser_info\x18\x02 \x01(\x0b\x32\x10.common.UserInfo"u\n\x1e\x46indVacanciesIDByUserIDRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\r\x12\x0e\n\x06offset\x18\x03 \x01(\r\x12#\n\tuser_info\x18\x04 \x01(\x0b\x32\x10.common.UserInfo"h\n\x1f\x46indVacanciesIDByUserIDResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\r\x12\x0e\n\x06offset\x18\x03 \x01(\r\x12\x15\n\rvacancies_ids\x18\x04 \x03(\x04\x32\xfe\x01\n\x12\x41pplicationService\x12.\n\x06Health\x12\r.common.Empty\x1a\x15.common.ServiceStatus\x12J\n\x12UpdateApplications\x12".vacancy.UpdateApplicationsRequest\x1a\x10.common.Response\x12l\n\x17\x46indVacanciesIDByUserID\x12\'.vacancy.FindVacanciesIDByUserIDRequest\x1a(.vacancy.FindVacanciesIDByUserIDResponseB\x16Z\x14pkg/applications_apib\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "applications_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = b"Z\024pkg/applications_api"
    _globals["_UPDATEAPPLICATIONSREQUEST"]._serialized_start = 45
    _globals["_UPDATEAPPLICATIONSREQUEST"]._serialized_end = 129
    _globals["_FINDVACANCIESIDBYUSERIDREQUEST"]._serialized_start = 131
    _globals["_FINDVACANCIESIDBYUSERIDREQUEST"]._serialized_end = 248
    _globals["_FINDVACANCIESIDBYUSERIDRESPONSE"]._serialized_start = 250
    _globals["_FINDVACANCIESIDBYUSERIDRESPONSE"]._serialized_end = 354
    _globals["_APPLICATIONSERVICE"]._serialized_start = 357
    _globals["_APPLICATIONSERVICE"]._serialized_end = 611
# @@protoc_insertion_point(module_scope)
