// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: protos/applications.proto

package applications_api

import (
	common "github.com/IvanDrf/work-hunter/pkg/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateApplicationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VacancyId     uint64                 `protobuf:"varint,1,opt,name=vacancy_id,json=vacancyId,proto3" json:"vacancy_id,omitempty"`
	UserInfo      *common.UserInfo       `protobuf:"bytes,2,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateApplicationsRequest) Reset() {
	*x = UpdateApplicationsRequest{}
	mi := &file_protos_applications_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateApplicationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateApplicationsRequest) ProtoMessage() {}

func (x *UpdateApplicationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_applications_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateApplicationsRequest.ProtoReflect.Descriptor instead.
func (*UpdateApplicationsRequest) Descriptor() ([]byte, []int) {
	return file_protos_applications_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateApplicationsRequest) GetVacancyId() uint64 {
	if x != nil {
		return x.VacancyId
	}
	return 0
}

func (x *UpdateApplicationsRequest) GetUserInfo() *common.UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

type FindVacanciesIDByUserIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserInfo      *common.UserInfo       `protobuf:"bytes,2,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindVacanciesIDByUserIDRequest) Reset() {
	*x = FindVacanciesIDByUserIDRequest{}
	mi := &file_protos_applications_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindVacanciesIDByUserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindVacanciesIDByUserIDRequest) ProtoMessage() {}

func (x *FindVacanciesIDByUserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_applications_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindVacanciesIDByUserIDRequest.ProtoReflect.Descriptor instead.
func (*FindVacanciesIDByUserIDRequest) Descriptor() ([]byte, []int) {
	return file_protos_applications_proto_rawDescGZIP(), []int{1}
}

func (x *FindVacanciesIDByUserIDRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FindVacanciesIDByUserIDRequest) GetUserInfo() *common.UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

type FindVacanciesIDByUserIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VacanciesIds  []string               `protobuf:"bytes,2,rep,name=vacancies_ids,json=vacanciesIds,proto3" json:"vacancies_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindVacanciesIDByUserIDResponse) Reset() {
	*x = FindVacanciesIDByUserIDResponse{}
	mi := &file_protos_applications_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindVacanciesIDByUserIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindVacanciesIDByUserIDResponse) ProtoMessage() {}

func (x *FindVacanciesIDByUserIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_applications_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindVacanciesIDByUserIDResponse.ProtoReflect.Descriptor instead.
func (*FindVacanciesIDByUserIDResponse) Descriptor() ([]byte, []int) {
	return file_protos_applications_proto_rawDescGZIP(), []int{2}
}

func (x *FindVacanciesIDByUserIDResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FindVacanciesIDByUserIDResponse) GetVacanciesIds() []string {
	if x != nil {
		return x.VacanciesIds
	}
	return nil
}

var File_protos_applications_proto protoreflect.FileDescriptor

const file_protos_applications_proto_rawDesc = "" +
	"\n" +
	"\x19protos/applications.proto\x12\avacancy\x1a\fcommon.proto\"i\n" +
	"\x19UpdateApplicationsRequest\x12\x1d\n" +
	"\n" +
	"vacancy_id\x18\x01 \x01(\x04R\tvacancyId\x12-\n" +
	"\tuser_info\x18\x02 \x01(\v2\x10.common.UserInfoR\buserInfo\"h\n" +
	"\x1eFindVacanciesIDByUserIDRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12-\n" +
	"\tuser_info\x18\x02 \x01(\v2\x10.common.UserInfoR\buserInfo\"_\n" +
	"\x1fFindVacanciesIDByUserIDResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rvacancies_ids\x18\x02 \x03(\tR\fvacanciesIds2\xfe\x01\n" +
	"\x12ApplicationService\x12.\n" +
	"\x06Health\x12\r.common.Empty\x1a\x15.common.ServiceStatus\x12J\n" +
	"\x12UpdateApplications\x12\".vacancy.UpdateApplicationsRequest\x1a\x10.common.Response\x12l\n" +
	"\x17FindVacanciesIDByUserID\x12'.vacancy.FindVacanciesIDByUserIDRequest\x1a(.vacancy.FindVacanciesIDByUserIDResponseB\x16Z\x14pkg/applications_apib\x06proto3"

var (
	file_protos_applications_proto_rawDescOnce sync.Once
	file_protos_applications_proto_rawDescData []byte
)

func file_protos_applications_proto_rawDescGZIP() []byte {
	file_protos_applications_proto_rawDescOnce.Do(func() {
		file_protos_applications_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_applications_proto_rawDesc), len(file_protos_applications_proto_rawDesc)))
	})
	return file_protos_applications_proto_rawDescData
}

var file_protos_applications_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protos_applications_proto_goTypes = []any{
	(*UpdateApplicationsRequest)(nil),       // 0: vacancy.UpdateApplicationsRequest
	(*FindVacanciesIDByUserIDRequest)(nil),  // 1: vacancy.FindVacanciesIDByUserIDRequest
	(*FindVacanciesIDByUserIDResponse)(nil), // 2: vacancy.FindVacanciesIDByUserIDResponse
	(*common.UserInfo)(nil),                 // 3: common.UserInfo
	(*common.Empty)(nil),                    // 4: common.Empty
	(*common.ServiceStatus)(nil),            // 5: common.ServiceStatus
	(*common.Response)(nil),                 // 6: common.Response
}
var file_protos_applications_proto_depIdxs = []int32{
	3, // 0: vacancy.UpdateApplicationsRequest.user_info:type_name -> common.UserInfo
	3, // 1: vacancy.FindVacanciesIDByUserIDRequest.user_info:type_name -> common.UserInfo
	4, // 2: vacancy.ApplicationService.Health:input_type -> common.Empty
	0, // 3: vacancy.ApplicationService.UpdateApplications:input_type -> vacancy.UpdateApplicationsRequest
	1, // 4: vacancy.ApplicationService.FindVacanciesIDByUserID:input_type -> vacancy.FindVacanciesIDByUserIDRequest
	5, // 5: vacancy.ApplicationService.Health:output_type -> common.ServiceStatus
	6, // 6: vacancy.ApplicationService.UpdateApplications:output_type -> common.Response
	2, // 7: vacancy.ApplicationService.FindVacanciesIDByUserID:output_type -> vacancy.FindVacanciesIDByUserIDResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protos_applications_proto_init() }
func file_protos_applications_proto_init() {
	if File_protos_applications_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_applications_proto_rawDesc), len(file_protos_applications_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_applications_proto_goTypes,
		DependencyIndexes: file_protos_applications_proto_depIdxs,
		MessageInfos:      file_protos_applications_proto_msgTypes,
	}.Build()
	File_protos_applications_proto = out.File
	file_protos_applications_proto_goTypes = nil
	file_protos_applications_proto_depIdxs = nil
}
