version: '3.9'

services:
  database:
    image: postgres:17.10
    container_name: "applications_database"
    restart: always

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}

    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

    networks:
    - applications_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5

  broker:
    image: rabbitmq:4.3.0
    container_name: vacancy_applications_broker
    ports:
      - "${RABBITMQ_OUTPUT_PORT}:5672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - applications_network
      - shared_network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_port_connectivity"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s

  applications_app:
    build:
      context: ..
      dockerfile: applications/Dockerfile
    container_name: applications_app

    ports:
      - "${APP_PORT}:50053"
    depends_on:
      database:
        condition: service_healthy

    networks:
      - applications_network

    restart: on-failure

volumes:
  pgdata:
  rabbitmq_data:

networks:
  applications_network:
    name: applications_network
    driver: bridge
  shared_network:
    external: true
    name: shared_network
    driver: bridge

