app:
  logger_level: debug
  host: localhost
  port: 50051

#postgresql
database:
  host: localhost
  port: 5432

  username: username
  password: password

  db_name: auth

#rabbitmq
broker:
  host: localhost
  port: 5672

  username: username
  password: password
  
  producer_queue: emails
  consumer_queue: emails

jwt:
  secret:  secret
  access_time: 15m
  refresh_time: 1080m