app:
  logger_level: debug
  host: localhost
  port: 50051

database:
  host: localhost
  port: 5432

  username: username
  password: password

  db_name: auth

jwt:
  secret:  secret
  access_time: 15m
  refresh_time: 1080m