app:
  logger_level: debug
  host: localhost
  port: 50051

#postgresql
database:
  host: localhost
  port: 5432

  username: ivan 
  password: 123

  db_name: auth

# rabbitmq
broker:
  host: localhost
  port: 5672

  username: ivan
  password: 123
  
  producer_queue: emails
  consumer_queue: emails

# email
email:
  host_addr: smtp.gmail.com:587
  username: shackovsku@gmail.com
  password: "eazk silw eoei cubk"

jwt:
  secret:  "0kNFFRUYOXY1aYewT1jKIf7Oprafhw8nh3ym5Dqo2hwHxduKCvVZTiYnMLtLiWuvIt28NyVK7PWERspUoAhAiw1fVqN2h5lnnEaUytxHzCF42wC9OfvwiAH4KJhar3AnXQS8jqenRsA38kiP5Iuf2kLhyCDbGfqGM0FKBdiYgrAgC9grabJLs7y7go6o7bLL4Hol3hm3Rv0mP1uSCgC10qDEX0ZJYQ6zfrwO1rSJMXTwrI30B3vGslhszyKBkavy"
  access_time: 15m
  refresh_time: 1080m