from typing import Protocol, Self
from uuid import UUID

from src.domain.models import ApplicationORM
from src.domain.schemas import ApplicationMessage


class IUnitOfWork(Protocol):
    async def __aenter__(self) -> Self: ...
    async def __aexit__(self, exc_type, exc, tb): ...

    async def commit(self): ...
    async def flush(self): ...
    async def rollback(self): ...

    async def stop(self) -> None: ...


class IApplicationRepo(Protocol):
    async def add_application(self, uof: IUnitOfWork, application: ApplicationORM) -> None: ...

    async def find_application(self, uof: IUnitOfWork, vacancy_id: int, user_id: UUID) -> ApplicationORM | None: ...
    async def find_vacancies_ids_by_user_id(
        self,
        uof: IUnitOfWork,
        user_id: UUID,
        *,
        limit: int,
        offset: int,
    ) -> list[int] | None: ...


class IApplicationProducer(Protocol):
    async def publish_applications(self, messages: list[ApplicationMessage]) -> None: ...

    async def stop(self) -> None: ...


class IMessageBox[T](Protocol):
    def add_message(self, message: T) -> None: ...
    def drop_box(self) -> None: ...
    def get_messages(self) -> list[T | None]: ...


class IMessageSaver(Protocol):
    async def save_messages(self, messages: list[ApplicationMessage]) -> None: ...
    async def get_last_messages(self, size: int) -> list[ApplicationMessage] | None: ...

    async def close(self) -> None: ...
