// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: protos/common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserRole int32

const (
	UserRole_UNSPECIFIED UserRole = 0
	UserRole_ADMIN       UserRole = 1
	UserRole_EMPLOYEE    UserRole = 2
	UserRole_EMPLOYER    UserRole = 3
)

// Enum value maps for UserRole.
var (
	UserRole_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "ADMIN",
		2: "EMPLOYEE",
		3: "EMPLOYER",
	}
	UserRole_value = map[string]int32{
		"UNSPECIFIED": 0,
		"ADMIN":       1,
		"EMPLOYEE":    2,
		"EMPLOYER":    3,
	}
)

func (x UserRole) Enum() *UserRole {
	p := new(UserRole)
	*p = x
	return p
}

func (x UserRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserRole) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_common_proto_enumTypes[0].Descriptor()
}

func (UserRole) Type() protoreflect.EnumType {
	return &file_protos_common_proto_enumTypes[0]
}

func (x UserRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserRole.Descriptor instead.
func (UserRole) EnumDescriptor() ([]byte, []int) {
	return file_protos_common_proto_rawDescGZIP(), []int{0}
}

// service status
type Status int32

const (
	Status_UNAVAILABLE Status = 0
	Status_AVAILABLE   Status = 1
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "UNAVAILABLE",
		1: "AVAILABLE",
	}
	Status_value = map[string]int32{
		"UNAVAILABLE": 0,
		"AVAILABLE":   1,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_common_proto_enumTypes[1].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_protos_common_proto_enumTypes[1]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_protos_common_proto_rawDescGZIP(), []int{1}
}

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          UserRole               `protobuf:"varint,1,opt,name=role,proto3,enum=common.UserRole" json:"role,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // uuid
	Verificated   bool                   `protobuf:"varint,3,opt,name=verificated,proto3" json:"verificated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_protos_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protos_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_protos_common_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfo) GetRole() UserRole {
	if x != nil {
		return x.Role
	}
	return UserRole_UNSPECIFIED
}

func (x *UserInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserInfo) GetVerificated() bool {
	if x != nil {
		return x.Verificated
	}
	return false
}

type FullUserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          UserRole               `protobuf:"varint,1,opt,name=role,proto3,enum=common.UserRole" json:"role,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Verificated   bool                   `protobuf:"varint,4,opt,name=verificated,proto3" json:"verificated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FullUserInfo) Reset() {
	*x = FullUserInfo{}
	mi := &file_protos_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FullUserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullUserInfo) ProtoMessage() {}

func (x *FullUserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protos_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullUserInfo.ProtoReflect.Descriptor instead.
func (*FullUserInfo) Descriptor() ([]byte, []int) {
	return file_protos_common_proto_rawDescGZIP(), []int{1}
}

func (x *FullUserInfo) GetRole() UserRole {
	if x != nil {
		return x.Role
	}
	return UserRole_UNSPECIFIED
}

func (x *FullUserInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FullUserInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *FullUserInfo) GetVerificated() bool {
	if x != nil {
		return x.Verificated
	}
	return false
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_protos_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_protos_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_protos_common_proto_rawDescGZIP(), []int{2}
}

type ServiceStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=common.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceStatus) Reset() {
	*x = ServiceStatus{}
	mi := &file_protos_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceStatus) ProtoMessage() {}

func (x *ServiceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_protos_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceStatus.ProtoReflect.Descriptor instead.
func (*ServiceStatus) Descriptor() ([]byte, []int) {
	return file_protos_common_proto_rawDescGZIP(), []int{3}
}

func (x *ServiceStatus) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_UNAVAILABLE
}

var File_protos_common_proto protoreflect.FileDescriptor

const file_protos_common_proto_rawDesc = "" +
	"\n" +
	"\x13protos/common.proto\x12\x06common\"k\n" +
	"\bUserInfo\x12$\n" +
	"\x04role\x18\x01 \x01(\x0e2\x10.common.UserRoleR\x04role\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12 \n" +
	"\vverificated\x18\x03 \x01(\bR\vverificated\"\x8b\x01\n" +
	"\fFullUserInfo\x12$\n" +
	"\x04role\x18\x01 \x01(\x0e2\x10.common.UserRoleR\x04role\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12 \n" +
	"\vverificated\x18\x04 \x01(\bR\vverificated\"\a\n" +
	"\x05Empty\"7\n" +
	"\rServiceStatus\x12&\n" +
	"\x06status\x18\x01 \x01(\x0e2\x0e.common.StatusR\x06status*B\n" +
	"\bUserRole\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\t\n" +
	"\x05ADMIN\x10\x01\x12\f\n" +
	"\bEMPLOYEE\x10\x02\x12\f\n" +
	"\bEMPLOYER\x10\x03*(\n" +
	"\x06Status\x12\x0f\n" +
	"\vUNAVAILABLE\x10\x00\x12\r\n" +
	"\tAVAILABLE\x10\x01B\fZ\n" +
	"pkg/commonb\x06proto3"

var (
	file_protos_common_proto_rawDescOnce sync.Once
	file_protos_common_proto_rawDescData []byte
)

func file_protos_common_proto_rawDescGZIP() []byte {
	file_protos_common_proto_rawDescOnce.Do(func() {
		file_protos_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_common_proto_rawDesc), len(file_protos_common_proto_rawDesc)))
	})
	return file_protos_common_proto_rawDescData
}

var file_protos_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_protos_common_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protos_common_proto_goTypes = []any{
	(UserRole)(0),         // 0: common.UserRole
	(Status)(0),           // 1: common.Status
	(*UserInfo)(nil),      // 2: common.UserInfo
	(*FullUserInfo)(nil),  // 3: common.FullUserInfo
	(*Empty)(nil),         // 4: common.Empty
	(*ServiceStatus)(nil), // 5: common.ServiceStatus
}
var file_protos_common_proto_depIdxs = []int32{
	0, // 0: common.UserInfo.role:type_name -> common.UserRole
	0, // 1: common.FullUserInfo.role:type_name -> common.UserRole
	1, // 2: common.ServiceStatus.status:type_name -> common.Status
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_protos_common_proto_init() }
func file_protos_common_proto_init() {
	if File_protos_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_common_proto_rawDesc), len(file_protos_common_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_common_proto_goTypes,
		DependencyIndexes: file_protos_common_proto_depIdxs,
		EnumInfos:         file_protos_common_proto_enumTypes,
		MessageInfos:      file_protos_common_proto_msgTypes,
	}.Build()
	File_protos_common_proto = out.File
	file_protos_common_proto_goTypes = nil
	file_protos_common_proto_depIdxs = nil
}
