// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: protos/auth.proto

package auth_api

import (
	common "github.com/IvanDrf/work-hunter/pkg/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Role          common.UserRole        `protobuf:"varint,3,opt,name=role,proto3,enum=common.UserRole" json:"role,omitempty"` // ADMIN, EMPLOYEE, EMPLOYER
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_protos_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_protos_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_protos_auth_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *User) GetRole() common.UserRole {
	if x != nil {
		return x.Role
	}
	return common.UserRole(0)
}

type AccessToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Access        string                 `protobuf:"bytes,1,opt,name=access,proto3" json:"access,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessToken) Reset() {
	*x = AccessToken{}
	mi := &file_protos_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessToken) ProtoMessage() {}

func (x *AccessToken) ProtoReflect() protoreflect.Message {
	mi := &file_protos_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessToken.ProtoReflect.Descriptor instead.
func (*AccessToken) Descriptor() ([]byte, []int) {
	return file_protos_auth_proto_rawDescGZIP(), []int{1}
}

func (x *AccessToken) GetAccess() string {
	if x != nil {
		return x.Access
	}
	return ""
}

type RefreshToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Refresh       string                 `protobuf:"bytes,1,opt,name=refresh,proto3" json:"refresh,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshToken) Reset() {
	*x = RefreshToken{}
	mi := &file_protos_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshToken) ProtoMessage() {}

func (x *RefreshToken) ProtoReflect() protoreflect.Message {
	mi := &file_protos_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshToken.ProtoReflect.Descriptor instead.
func (*RefreshToken) Descriptor() ([]byte, []int) {
	return file_protos_auth_proto_rawDescGZIP(), []int{2}
}

func (x *RefreshToken) GetRefresh() string {
	if x != nil {
		return x.Refresh
	}
	return ""
}

type JwtTokens struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Access        string                 `protobuf:"bytes,1,opt,name=access,proto3" json:"access,omitempty"`
	Refresh       string                 `protobuf:"bytes,2,opt,name=refresh,proto3" json:"refresh,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JwtTokens) Reset() {
	*x = JwtTokens{}
	mi := &file_protos_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JwtTokens) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwtTokens) ProtoMessage() {}

func (x *JwtTokens) ProtoReflect() protoreflect.Message {
	mi := &file_protos_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwtTokens.ProtoReflect.Descriptor instead.
func (*JwtTokens) Descriptor() ([]byte, []int) {
	return file_protos_auth_proto_rawDescGZIP(), []int{3}
}

func (x *JwtTokens) GetAccess() string {
	if x != nil {
		return x.Access
	}
	return ""
}

func (x *JwtTokens) GetRefresh() string {
	if x != nil {
		return x.Refresh
	}
	return ""
}

type TokenPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Verificated   bool                   `protobuf:"varint,2,opt,name=verificated,proto3" json:"verificated,omitempty"`
	Role          common.UserRole        `protobuf:"varint,3,opt,name=role,proto3,enum=common.UserRole" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenPayload) Reset() {
	*x = TokenPayload{}
	mi := &file_protos_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenPayload) ProtoMessage() {}

func (x *TokenPayload) ProtoReflect() protoreflect.Message {
	mi := &file_protos_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenPayload.ProtoReflect.Descriptor instead.
func (*TokenPayload) Descriptor() ([]byte, []int) {
	return file_protos_auth_proto_rawDescGZIP(), []int{4}
}

func (x *TokenPayload) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TokenPayload) GetVerificated() bool {
	if x != nil {
		return x.Verificated
	}
	return false
}

func (x *TokenPayload) GetRole() common.UserRole {
	if x != nil {
		return x.Role
	}
	return common.UserRole(0)
}

type VerifToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifToken) Reset() {
	*x = VerifToken{}
	mi := &file_protos_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifToken) ProtoMessage() {}

func (x *VerifToken) ProtoReflect() protoreflect.Message {
	mi := &file_protos_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifToken.ProtoReflect.Descriptor instead.
func (*VerifToken) Descriptor() ([]byte, []int) {
	return file_protos_auth_proto_rawDescGZIP(), []int{5}
}

func (x *VerifToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Access        string                 `protobuf:"bytes,1,opt,name=access,proto3" json:"access,omitempty"`     // access jwt token
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"` // user password
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_protos_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_protos_auth_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteUserRequest) GetAccess() string {
	if x != nil {
		return x.Access
	}
	return ""
}

func (x *DeleteUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ChangePasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Access        string                 `protobuf:"bytes,1,opt,name=access,proto3" json:"access,omitempty"` // access jwt token
	Old           string                 `protobuf:"bytes,2,opt,name=old,proto3" json:"old,omitempty"`       // old password
	New           string                 `protobuf:"bytes,3,opt,name=new,proto3" json:"new,omitempty"`       // new password
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordRequest) Reset() {
	*x = ChangePasswordRequest{}
	mi := &file_protos_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordRequest) ProtoMessage() {}

func (x *ChangePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordRequest.ProtoReflect.Descriptor instead.
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return file_protos_auth_proto_rawDescGZIP(), []int{7}
}

func (x *ChangePasswordRequest) GetAccess() string {
	if x != nil {
		return x.Access
	}
	return ""
}

func (x *ChangePasswordRequest) GetOld() string {
	if x != nil {
		return x.Old
	}
	return ""
}

func (x *ChangePasswordRequest) GetNew() string {
	if x != nil {
		return x.New
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_protos_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_protos_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_protos_auth_proto_rawDescGZIP(), []int{8}
}

var File_protos_auth_proto protoreflect.FileDescriptor

const file_protos_auth_proto_rawDesc = "" +
	"\n" +
	"\x11protos/auth.proto\x12\x04auth\x1a\fcommon.proto\"^\n" +
	"\x04User\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12$\n" +
	"\x04role\x18\x03 \x01(\x0e2\x10.common.UserRoleR\x04role\"%\n" +
	"\vAccessToken\x12\x16\n" +
	"\x06access\x18\x01 \x01(\tR\x06access\"(\n" +
	"\fRefreshToken\x12\x18\n" +
	"\arefresh\x18\x01 \x01(\tR\arefresh\"=\n" +
	"\tJwtTokens\x12\x16\n" +
	"\x06access\x18\x01 \x01(\tR\x06access\x12\x18\n" +
	"\arefresh\x18\x02 \x01(\tR\arefresh\"f\n" +
	"\fTokenPayload\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vverificated\x18\x02 \x01(\bR\vverificated\x12$\n" +
	"\x04role\x18\x03 \x01(\x0e2\x10.common.UserRoleR\x04role\"\"\n" +
	"\n" +
	"VerifToken\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"G\n" +
	"\x11DeleteUserRequest\x12\x16\n" +
	"\x06access\x18\x01 \x01(\tR\x06access\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"S\n" +
	"\x15ChangePasswordRequest\x12\x16\n" +
	"\x06access\x18\x01 \x01(\tR\x06access\x12\x10\n" +
	"\x03old\x18\x02 \x01(\tR\x03old\x12\x10\n" +
	"\x03new\x18\x03 \x01(\tR\x03new\"\a\n" +
	"\x05Empty2\xcd\x03\n" +
	"\x04Auth\x12.\n" +
	"\x06Health\x12\r.common.Empty\x1a\x15.common.ServiceStatus\x12'\n" +
	"\bRegister\x12\n" +
	".auth.User\x1a\x0f.auth.JwtTokens\x12$\n" +
	"\x05Login\x12\n" +
	".auth.User\x1a\x0f.auth.JwtTokens\x122\n" +
	"\n" +
	"DeleteUser\x12\x17.auth.DeleteUserRequest\x1a\v.auth.Empty\x12:\n" +
	"\x0eChangePassword\x12\x1b.auth.ChangePasswordRequest\x1a\v.auth.Empty\x127\n" +
	"\x15SendVerificationEmail\x12\x11.auth.AccessToken\x1a\v.auth.Empty\x120\n" +
	"\vVerifyEmail\x12\x10.auth.VerifToken\x1a\x0f.auth.JwtTokens\x125\n" +
	"\fIsTokenValid\x12\x11.auth.AccessToken\x1a\x12.auth.TokenPayload\x124\n" +
	"\rRefreshTokens\x12\x12.auth.RefreshToken\x1a\x0f.auth.JwtTokensB\x0eZ\fpkg/auth-apib\x06proto3"

var (
	file_protos_auth_proto_rawDescOnce sync.Once
	file_protos_auth_proto_rawDescData []byte
)

func file_protos_auth_proto_rawDescGZIP() []byte {
	file_protos_auth_proto_rawDescOnce.Do(func() {
		file_protos_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_auth_proto_rawDesc), len(file_protos_auth_proto_rawDesc)))
	})
	return file_protos_auth_proto_rawDescData
}

var file_protos_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_protos_auth_proto_goTypes = []any{
	(*User)(nil),                  // 0: auth.User
	(*AccessToken)(nil),           // 1: auth.AccessToken
	(*RefreshToken)(nil),          // 2: auth.RefreshToken
	(*JwtTokens)(nil),             // 3: auth.JwtTokens
	(*TokenPayload)(nil),          // 4: auth.TokenPayload
	(*VerifToken)(nil),            // 5: auth.VerifToken
	(*DeleteUserRequest)(nil),     // 6: auth.DeleteUserRequest
	(*ChangePasswordRequest)(nil), // 7: auth.ChangePasswordRequest
	(*Empty)(nil),                 // 8: auth.Empty
	(common.UserRole)(0),          // 9: common.UserRole
	(*common.Empty)(nil),          // 10: common.Empty
	(*common.ServiceStatus)(nil),  // 11: common.ServiceStatus
}
var file_protos_auth_proto_depIdxs = []int32{
	9,  // 0: auth.User.role:type_name -> common.UserRole
	9,  // 1: auth.TokenPayload.role:type_name -> common.UserRole
	10, // 2: auth.Auth.Health:input_type -> common.Empty
	0,  // 3: auth.Auth.Register:input_type -> auth.User
	0,  // 4: auth.Auth.Login:input_type -> auth.User
	6,  // 5: auth.Auth.DeleteUser:input_type -> auth.DeleteUserRequest
	7,  // 6: auth.Auth.ChangePassword:input_type -> auth.ChangePasswordRequest
	1,  // 7: auth.Auth.SendVerificationEmail:input_type -> auth.AccessToken
	5,  // 8: auth.Auth.VerifyEmail:input_type -> auth.VerifToken
	1,  // 9: auth.Auth.IsTokenValid:input_type -> auth.AccessToken
	2,  // 10: auth.Auth.RefreshTokens:input_type -> auth.RefreshToken
	11, // 11: auth.Auth.Health:output_type -> common.ServiceStatus
	3,  // 12: auth.Auth.Register:output_type -> auth.JwtTokens
	3,  // 13: auth.Auth.Login:output_type -> auth.JwtTokens
	8,  // 14: auth.Auth.DeleteUser:output_type -> auth.Empty
	8,  // 15: auth.Auth.ChangePassword:output_type -> auth.Empty
	8,  // 16: auth.Auth.SendVerificationEmail:output_type -> auth.Empty
	3,  // 17: auth.Auth.VerifyEmail:output_type -> auth.JwtTokens
	4,  // 18: auth.Auth.IsTokenValid:output_type -> auth.TokenPayload
	3,  // 19: auth.Auth.RefreshTokens:output_type -> auth.JwtTokens
	11, // [11:20] is the sub-list for method output_type
	2,  // [2:11] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_protos_auth_proto_init() }
func file_protos_auth_proto_init() {
	if File_protos_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_auth_proto_rawDesc), len(file_protos_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_auth_proto_goTypes,
		DependencyIndexes: file_protos_auth_proto_depIdxs,
		MessageInfos:      file_protos_auth_proto_msgTypes,
	}.Build()
	File_protos_auth_proto = out.File
	file_protos_auth_proto_goTypes = nil
	file_protos_auth_proto_depIdxs = nil
}
