// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: protos/auth.proto

package auth_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_protos_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_protos_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_protos_auth_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AccessToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Access        string                 `protobuf:"bytes,1,opt,name=access,proto3" json:"access,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessToken) Reset() {
	*x = AccessToken{}
	mi := &file_protos_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessToken) ProtoMessage() {}

func (x *AccessToken) ProtoReflect() protoreflect.Message {
	mi := &file_protos_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessToken.ProtoReflect.Descriptor instead.
func (*AccessToken) Descriptor() ([]byte, []int) {
	return file_protos_auth_proto_rawDescGZIP(), []int{1}
}

func (x *AccessToken) GetAccess() string {
	if x != nil {
		return x.Access
	}
	return ""
}

type RefreshToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Refresh       string                 `protobuf:"bytes,1,opt,name=refresh,proto3" json:"refresh,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshToken) Reset() {
	*x = RefreshToken{}
	mi := &file_protos_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshToken) ProtoMessage() {}

func (x *RefreshToken) ProtoReflect() protoreflect.Message {
	mi := &file_protos_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshToken.ProtoReflect.Descriptor instead.
func (*RefreshToken) Descriptor() ([]byte, []int) {
	return file_protos_auth_proto_rawDescGZIP(), []int{2}
}

func (x *RefreshToken) GetRefresh() string {
	if x != nil {
		return x.Refresh
	}
	return ""
}

type JwtTokens struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Access        string                 `protobuf:"bytes,1,opt,name=access,proto3" json:"access,omitempty"`
	Refresh       string                 `protobuf:"bytes,2,opt,name=refresh,proto3" json:"refresh,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JwtTokens) Reset() {
	*x = JwtTokens{}
	mi := &file_protos_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JwtTokens) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwtTokens) ProtoMessage() {}

func (x *JwtTokens) ProtoReflect() protoreflect.Message {
	mi := &file_protos_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwtTokens.ProtoReflect.Descriptor instead.
func (*JwtTokens) Descriptor() ([]byte, []int) {
	return file_protos_auth_proto_rawDescGZIP(), []int{3}
}

func (x *JwtTokens) GetAccess() string {
	if x != nil {
		return x.Access
	}
	return ""
}

func (x *JwtTokens) GetRefresh() string {
	if x != nil {
		return x.Refresh
	}
	return ""
}

type TokenPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Verificated   bool                   `protobuf:"varint,2,opt,name=verificated,proto3" json:"verificated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenPayload) Reset() {
	*x = TokenPayload{}
	mi := &file_protos_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenPayload) ProtoMessage() {}

func (x *TokenPayload) ProtoReflect() protoreflect.Message {
	mi := &file_protos_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenPayload.ProtoReflect.Descriptor instead.
func (*TokenPayload) Descriptor() ([]byte, []int) {
	return file_protos_auth_proto_rawDescGZIP(), []int{4}
}

func (x *TokenPayload) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TokenPayload) GetVerificated() bool {
	if x != nil {
		return x.Verificated
	}
	return false
}

type Email struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Email) Reset() {
	*x = Email{}
	mi := &file_protos_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Email) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Email) ProtoMessage() {}

func (x *Email) ProtoReflect() protoreflect.Message {
	mi := &file_protos_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Email.ProtoReflect.Descriptor instead.
func (*Email) Descriptor() ([]byte, []int) {
	return file_protos_auth_proto_rawDescGZIP(), []int{5}
}

func (x *Email) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type AcceptStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptStatus) Reset() {
	*x = AcceptStatus{}
	mi := &file_protos_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptStatus) ProtoMessage() {}

func (x *AcceptStatus) ProtoReflect() protoreflect.Message {
	mi := &file_protos_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptStatus.ProtoReflect.Descriptor instead.
func (*AcceptStatus) Descriptor() ([]byte, []int) {
	return file_protos_auth_proto_rawDescGZIP(), []int{6}
}

func (x *AcceptStatus) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

var File_protos_auth_proto protoreflect.FileDescriptor

const file_protos_auth_proto_rawDesc = "" +
	"\n" +
	"\x11protos/auth.proto\x12\x04auth\"8\n" +
	"\x04User\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"%\n" +
	"\vAccessToken\x12\x16\n" +
	"\x06access\x18\x01 \x01(\tR\x06access\"(\n" +
	"\fRefreshToken\x12\x18\n" +
	"\arefresh\x18\x01 \x01(\tR\arefresh\"=\n" +
	"\tJwtTokens\x12\x16\n" +
	"\x06access\x18\x01 \x01(\tR\x06access\x12\x18\n" +
	"\arefresh\x18\x02 \x01(\tR\arefresh\"@\n" +
	"\fTokenPayload\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vverificated\x18\x02 \x01(\bR\vverificated\"\x1d\n" +
	"\x05Email\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"*\n" +
	"\fAcceptStatus\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted2\xa9\x02\n" +
	"\x04Auth\x12'\n" +
	"\bRegister\x12\n" +
	".auth.User\x1a\x0f.auth.JwtTokens\x12$\n" +
	"\x05Login\x12\n" +
	".auth.User\x1a\x0f.auth.JwtTokens\x128\n" +
	"\x15SendVerificationEmail\x12\v.auth.Email\x1a\x12.auth.AcceptStatus\x12+\n" +
	"\vVerifyEmail\x12\v.auth.Email\x1a\x0f.auth.JwtTokens\x125\n" +
	"\fIsTokenValid\x12\x11.auth.AccessToken\x1a\x12.auth.TokenPayload\x124\n" +
	"\rRefreshTokens\x12\x12.auth.RefreshToken\x1a\x0f.auth.JwtTokensB\x0eZ\fpkg/auth-apib\x06proto3"

var (
	file_protos_auth_proto_rawDescOnce sync.Once
	file_protos_auth_proto_rawDescData []byte
)

func file_protos_auth_proto_rawDescGZIP() []byte {
	file_protos_auth_proto_rawDescOnce.Do(func() {
		file_protos_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_auth_proto_rawDesc), len(file_protos_auth_proto_rawDesc)))
	})
	return file_protos_auth_proto_rawDescData
}

var file_protos_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_protos_auth_proto_goTypes = []any{
	(*User)(nil),         // 0: auth.User
	(*AccessToken)(nil),  // 1: auth.AccessToken
	(*RefreshToken)(nil), // 2: auth.RefreshToken
	(*JwtTokens)(nil),    // 3: auth.JwtTokens
	(*TokenPayload)(nil), // 4: auth.TokenPayload
	(*Email)(nil),        // 5: auth.Email
	(*AcceptStatus)(nil), // 6: auth.AcceptStatus
}
var file_protos_auth_proto_depIdxs = []int32{
	0, // 0: auth.Auth.Register:input_type -> auth.User
	0, // 1: auth.Auth.Login:input_type -> auth.User
	5, // 2: auth.Auth.SendVerificationEmail:input_type -> auth.Email
	5, // 3: auth.Auth.VerifyEmail:input_type -> auth.Email
	1, // 4: auth.Auth.IsTokenValid:input_type -> auth.AccessToken
	2, // 5: auth.Auth.RefreshTokens:input_type -> auth.RefreshToken
	3, // 6: auth.Auth.Register:output_type -> auth.JwtTokens
	3, // 7: auth.Auth.Login:output_type -> auth.JwtTokens
	6, // 8: auth.Auth.SendVerificationEmail:output_type -> auth.AcceptStatus
	3, // 9: auth.Auth.VerifyEmail:output_type -> auth.JwtTokens
	4, // 10: auth.Auth.IsTokenValid:output_type -> auth.TokenPayload
	3, // 11: auth.Auth.RefreshTokens:output_type -> auth.JwtTokens
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_auth_proto_init() }
func file_protos_auth_proto_init() {
	if File_protos_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_auth_proto_rawDesc), len(file_protos_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_auth_proto_goTypes,
		DependencyIndexes: file_protos_auth_proto_depIdxs,
		MessageInfos:      file_protos_auth_proto_msgTypes,
	}.Build()
	File_protos_auth_proto = out.File
	file_protos_auth_proto_goTypes = nil
	file_protos_auth_proto_depIdxs = nil
}
