syntax = "proto3";

package vacancy;

option go_package = "pkg/applications_api";

import "common.proto";

service ApplicationService {
    rpc Health(common.Empty) returns (common.ServiceStatus);
    
    rpc UpdateApplications(UpdateApplicationsRequest) returns (common.Response);

    rpc FindVacanciesIDByUserID(FindVacanciesIDByUserIDRequest) returns (FindVacanciesIDByUserIDResponse);
}


message UpdateApplicationsRequest {
    uint64 vacancy_id = 1;

    common.UserInfo user_info = 2;
}

message FindVacanciesIDByUserIDRequest {
    string user_id = 1;
    uint32 limit = 2;
    uint32 offset = 3;

    common.UserInfo user_info = 4;
}

message FindVacanciesIDByUserIDResponse {
    string user_id = 1;
    uint32 limit = 2;
    uint32 offset = 3;

    repeated uint64 vacancies_ids = 4;
}