syntax = "proto3";

package common;

option go_package = "github.com/IvanDrf/work-hunter/pkg/common";

enum UserRole {
    UNSPECIFIED = 0;
    ADMIN = 1;
    EMPLOYEE = 2;
    EMPLOYER = 3;
}

message UserInfo {
    UserRole role = 1;
    string user_id = 2; // uuid
    bool verificated = 3;
}

message FullUserInfo {
    UserRole role = 1;
    string user_id = 2;
    string username = 3;
    bool verificated = 4;
}

message Empty {
}

// service status
enum Status { 
    UNAVAILABLE = 0;
    AVAILABLE = 1;
}

message ServiceStatus {
    Status status = 1;
}