syntax = "proto3";

package user;

option go_package = "pkg/user-api";

import "google/protobuf/timestamp.proto";
import "google/protobuf/empty.proto";

// User service for managing user profiles and data
service User {
     // Create a new user profile (called after successful registration in auth service)
    rpc CreateProfile(CreateProfileRequest) returns (UserProfile);

    // Get user profile by ID
    rpc GetProfile(GetProfileRequest) returns (UserProfile);

    // Get user profile by username
    rpc GetProfileByEmail(GetProfileByEmailRequest) returns (UserProfile);

    // Update user profile
    rpc UpdateProfile(UpdateProfileRequest) returns (UserProfile);

    // Delete user profile
    rpc DeleteProfile(DeleteProfileRequest) returns(google.protobuf.Empty);

    // admin operations
    // Update user status (active/inactive/blocked)
    rpc UpdateUserStatus(UpdateUserStatusRequest) returns (UserProfile);
    rpc ListUsers(ListUsersRequest) returns (ListUsersResponse);
}

enum UserStatus {
    USER_STATUS_UNSPECIFIED = 0;
    USER_STATUS_ACTIVE = 1;
    USER_STATUS_INACTIVE = 2;
    USER_STATUS_BLOCKED = 3;
    USER_STATUS_DELETED = 4;
}

enum UserRole {
    USER_ROLE_UNSPECIFIED = 0;
    USER_ROLE_EMPLOYEE = 1;
    USER_ROLE_EMPLOYER = 2;
    USER_ROLE_ADMIN = 3;
}

message UserProfile {
    string id = 1; // UUID
    string email = 2;
    optional string first_name = 3; 
    optional string last_name = 4;
    optional string company_name = 5;

    UserStatus status = 6; // Account status
    UserRole role = 7; // User role

    google.protobuf.Timestamp created_at = 8;
    google.protobuf.Timestamp updated_at = 9;

    bool verificated = 13;
}

message CreateProfileRequest {
    string user_id = 1; // User ID from auth service
    string email = 2;
    optional string first_name = 3;
    optional string last_name = 4;
    optional string company_name = 5;
    bool verificated = 6;
}

message GetProfileRequest {
    string user_id = 1;
}

message UpdateProfileRequest {
    string user_id = 1;
    optional string first_name = 2;
    optional string last_name = 3;
    optional string company_name = 4;
    optional bool verificated = 5;
}

message DeleteProfileRequest {
    string user_id = 1;
}

message GetProfileByEmailRequest {
    string email = 1;
}

message UpdateUserStatusRequest {
    string user_id = 1;
    UserStatus status = 2; // New profile status
}

message ListUsersRequest {
    int32 page_size = 1;
    UserStatus status = 2;
    UserRole role = 3;
    string serch_query = 4;
    string sort_by = 5;
    int32 offset = 6;
}

message ListUsersResponse {
    repeated UserProfile users = 1;
    int32 total_count = 2;
}