"""add author_name field in vacancies table

Revision ID: 75bcb6c66760
Revises: 4e510a03279f
Create Date: 2026-05-03 17:06:27.617593

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '75bcb6c66760'
down_revision: str | Sequence[str] | None = '4e510a03279f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('author_name', sa.VARCHAR(length=75), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancies', 'author_name')
    # ### end Alembic commands ###
