"""create tables

Revision ID: 6765fae4e0eb
Revises: df8946142513
Create Date: 2026-04-22 11:43:32.409027

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6765fae4e0eb'
down_revision: Union[str, Sequence[str], None] = 'df8946142513'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('tag_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('tag', sa.VARCHAR(length=40), nullable=False),
    sa.PrimaryKeyConstraint('tag_id')
    )
    op.create_index(op.f('ix_tags_tag'), 'tags', ['tag'], unique=True)
    op.create_index(op.f('ix_tags_tag_id'), 'tags', ['tag_id'], unique=False)
    op.create_table('vacancies',
    sa.Column('vacancy_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=False),
    sa.Column('conditions', sa.Text(), nullable=False),
    sa.Column('salary_min', sa.INTEGER(), nullable=False),
    sa.Column('salary_max', sa.INTEGER(), nullable=False),
    sa.Column('currency', sa.Enum('RUB', 'USD', 'EUR', name='currency'), nullable=False),
    sa.Column('city', sa.VARCHAR(length=150), nullable=True),
    sa.Column('metro', sa.VARCHAR(length=100), nullable=True),
    sa.Column('remote_type', sa.Enum('OFFICE', 'REMOTE', 'HYBRID', 'ANY', name='remotetype'), nullable=False),
    sa.Column('time_type', sa.Enum('FULL', 'PART', name='timetype'), nullable=False),
    sa.Column('experience_min', sa.INTEGER(), nullable=True),
    sa.Column('experience_max', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('published_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('closed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('status', sa.Enum('MODERATING', 'PUBLISHED', 'UPDATED', 'CLOSED', 'DELETED', name='vacancystatus'), nullable=False),
    sa.Column('moderated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('moderator_comments', sa.Text(), nullable=True),
    sa.Column('views', sa.BIGINT(), nullable=True),
    sa.Column('applications_count', sa.BIGINT(), nullable=False),
    sa.PrimaryKeyConstraint('vacancy_id')
    )
    op.create_index(op.f('ix_vacancies_vacancy_id'), 'vacancies', ['vacancy_id'], unique=False)
    op.create_table('vacancies_to_tags',
    sa.Column('vacancy_id', sa.BIGINT(), nullable=False),
    sa.Column('tag_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.tag_id'], ),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.vacancy_id'], ),
    sa.PrimaryKeyConstraint('vacancy_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacancies_to_tags')
    op.drop_index(op.f('ix_vacancies_vacancy_id'), table_name='vacancies')
    op.drop_table('vacancies')
    op.drop_index(op.f('ix_tags_tag_id'), table_name='tags')
    op.drop_index(op.f('ix_tags_tag'), table_name='tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
