"""make salary_min, salary_max None by default

Revision ID: d963ce632131
Revises: cb08f8def486
Create Date: 2026-06-08 18:58:51.782607

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "d963ce632131"
down_revision: Union[str, Sequence[str], None] = "cb08f8def486"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
