"""add author_id in vacancies table

Revision ID: d04fa6e6c6ae
Revises: 6765fae4e0eb
Create Date: 2026-04-22 14:34:05.354595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd04fa6e6c6ae'
down_revision: Union[str, Sequence[str], None] = '6765fae4e0eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('author_id', sa.UUID(), nullable=False))
    op.alter_column('vacancies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.create_index(op.f('ix_vacancies_author_id'), 'vacancies', ['author_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacancies_author_id'), table_name='vacancies')
    op.alter_column('vacancies', 'created_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('vacancies', 'author_id')
    # ### end Alembic commands ###
