"""change m2m constructions

Revision ID: 0ffd03b710da
Revises: d04fa6e6c6ae
Create Date: 2026-04-26 20:00:20.086550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ffd03b710da'
down_revision: Union[str, Sequence[str], None] = 'd04fa6e6c6ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('vacancies_to_tags_vacancy_id_fkey'), 'vacancies_to_tags', type_='foreignkey')
    op.drop_constraint(op.f('vacancies_to_tags_tag_id_fkey'), 'vacancies_to_tags', type_='foreignkey')
    op.create_foreign_key(None, 'vacancies_to_tags', 'vacancies', ['vacancy_id'], ['vacancy_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'vacancies_to_tags', 'tags', ['tag_id'], ['tag_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vacancies_to_tags', type_='foreignkey')
    op.drop_constraint(None, 'vacancies_to_tags', type_='foreignkey')
    op.create_foreign_key(op.f('vacancies_to_tags_tag_id_fkey'), 'vacancies_to_tags', 'tags', ['tag_id'], ['tag_id'])
    op.create_foreign_key(op.f('vacancies_to_tags_vacancy_id_fkey'), 'vacancies_to_tags', 'vacancies', ['vacancy_id'], ['vacancy_id'])
    # ### end Alembic commands ###
