"""add is_city_valid field

Revision ID: 0813a3d5e6b8
Revises: 7f6aee1fd83b
Create Date: 2026-07-09 11:33:33.975237

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0813a3d5e6b8'
down_revision: str | Sequence[str] | None = '7f6aee1fd83b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('is_city_valid', sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancies', 'is_city_valid')
    # ### end Alembic commands ###
