"""create tables

Revision ID: df8946142513
Revises: 
Create Date: 2026-04-22 11:41:56.911985

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'df8946142513'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
