"""make salary_max, salary_min nullable

Revision ID: a863e2e0f5cb
Revises: 75bcb6c66760
Create Date: 2026-05-18 23:58:12.920916

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a863e2e0f5cb"
down_revision: str | Sequence[str] | None = "75bcb6c66760"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("vacancies", "salary_min", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("vacancies", "salary_max", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("vacancies", "views", existing_type=sa.BIGINT(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("vacancies", "views", existing_type=sa.BIGINT(), nullable=True)
    op.alter_column("vacancies", "salary_max", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("vacancies", "salary_min", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
