"""add deleted_at field, if vacancy has been deleted

Revision ID: cb08f8def486
Revises: a863e2e0f5cb
Create Date: 2026-05-19 01:17:10.478236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb08f8def486'
down_revision: Union[str, Sequence[str], None] = 'a863e2e0f5cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancies', 'deleted_at')
    # ### end Alembic commands ###
