"""add is_metro_valid field

Revision ID: 7f6aee1fd83b
Revises: d963ce632131
Create Date: 2026-07-03 14:42:47.739282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f6aee1fd83b'
down_revision: Union[str, Sequence[str], None] = 'd963ce632131'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('is_metro_valid', sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancies', 'is_metro_valid')
    # ### end Alembic commands ###
