from typing import Protocol, Self


class IUnitOfWork(Protocol):
    async def __aenter__(self) -> Self: ...
    async def __aexit__(self, exc_type, exc, tb): ...

    async def commit(self): ...
    async def flush(self): ...
    async def rollback(self): ...

    async def stop(self) -> None: ...
