from typing import Protocol


class IUnitOfWork(Protocol):
    async def __aenter__(self) -> "IUnitOfWork": ...
    async def __aexit__(self, exc_type, exc, tb): ...

    async def commit(self): ...
    async def flush(self): ...
    async def rollback(self): ...
