from typing import Protocol


class ICityRepo(Protocol):
    async def is_city_exists(self, city: str) -> bool: ...
    async def close(self) -> None: ...


class IMetroRepo(Protocol):
    async def is_metro_exists(self, city: str, metro: str) -> bool: ...
    async def close(self) -> None: ...
