"""remove extra indexes

Revision ID: b7c7f8edd0bd
Revises: beb57b57305f
Create Date: 2026-07-06 17:15:31.315121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7c7f8edd0bd'
down_revision: Union[str, Sequence[str], None] = 'beb57b57305f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('unique_vacancy_id_user_id'), 'applications', type_='unique')
    op.drop_index(op.f('vacancy_index'), table_name='applications')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('vacancy_index'), 'applications', ['vacancy_id', 'user_id'], unique=False)
    op.create_unique_constraint(op.f('unique_vacancy_id_user_id'), 'applications', ['vacancy_id', 'user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
