"""add unique constraint for vacancy_id and user_id

Revision ID: beb57b57305f
Revises: 602ec24ee3ed
Create Date: 2026-07-06 17:11:40.860347

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "beb57b57305f"
down_revision: Union[str, Sequence[str], None] = "602ec24ee3ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("vacancy_index"), table_name="applications", postgresql_using="hash")
    op.create_index("vacancy_index", "applications", ["vacancy_id", "user_id"], unique=False)
    op.create_unique_constraint("unique_vacancy_id_user_id", "applications", ["vacancy_id", "user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_vacancy_id_user_id", "applications", type_="unique")
    op.drop_index("vacancy_index", table_name="applications", postgresql_using="hash")
    op.create_index(op.f("vacancy_index"), "applications", ["vacancy_id"], unique=False, postgresql_using="hash")
    # ### end Alembic commands ###
