"""add application model

Revision ID: 602ec24ee3ed
Revises:
Create Date: 2026-07-06 17:03:36.068349

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "602ec24ee3ed"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "applications",
        sa.Column("vacancy_id", sa.BIGINT(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("vacancy_id", "user_id"),
    )
    op.create_index("vacancy_index", "applications", ["vacancy_id"], postgresql_using="hash")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("vacancy_index", table_name="applications", postgresql_using="hash")
    op.drop_table("applications")
    # ### end Alembic commands ###
